### ISSUE TITLE
编译出错错误

### ISSUE THREAD

**Issue by lukemin** [tossp/redpill-tool-chain#1]
root@instance-20210811-1316:/home/ubuntu/redpill-tool-chain# ./redpill_tool_chain.sh auto bromolow-7.0.1-42218

Checking if redpill-lkm sources require pull.
  Nothing to do.
Check if redpill-load sources require pull.
  Nothing to do.
Lay back and enjoy the show: Magic is about to happen!
make[1]: Entering directory '/opt/redpill-lkm'
make -C /opt/toolkit_dev-bromolow-7.0.1-42218 M=/opt/redpill-lkm RP_MODULE_TARGET="dev" RP_MODULE_TARGET_VER="7" modules
make[2]: Entering directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
/opt/toolkit_dev-bromolow-7.0.1-42218/arch/x86/Makefile:164: CONFIG_RETPOLINE=y, but not supported by the compiler. Toolchain update recommended.
RP-TARGET SPECIFIED AS dev v7
  CC [M]  /opt/redpill-lkm/compat/string_compat.o
cc1: error: code model kernel does not support PIC mode
make[3]: *** [scripts/Makefile.build:309: /opt/redpill-lkm/compat/string_compat.o] Error 1
make[2]: *** [Makefile:1229: _module_/opt/redpill-lkm] Error 2
make[2]: Leaving directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
make[1]: *** [Makefile:90: dev-v7] Error 2
make[1]: Leaving directory '/opt/redpill-lkm'

**Comment by rodhammond** [comment]
Fixed? I'm seeing the same error 10 months later using latest Git pull:
cd  /var/lib/vz/dsm && chmod -R 777 ./* && ./redpill_tool_chain.sh auto ds3615xs-7.0.1-42218
Checking if redpill-lkm sources require pull.
  Nothing to do.
Check if redpill-load sources require pull.
  Nothing to do.
Lay back and enjoy the show: Magic is about to happen!
make[1]: Entering directory '/opt/redpill-lkm'
make -C /opt/toolkit_dev-bromolow-7.0.1-42218 M=/opt/redpill-lkm RP_MODULE_TARGET="dev" RP_MODULE_TARGET_VER="7" modules
make[2]: Entering directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
/opt/toolkit_dev-bromolow-7.0.1-42218/arch/x86/Makefile:164: CONFIG_RETPOLINE=y, but not supported by the compiler. Toolchain update recommended.
RP-TARGET SPECIFIED AS dev v7
  CC [M]  /opt/redpill-lkm/compat/string_compat.o
cc1: error: code model kernel does not support PIC mode
make[3]: *** [scripts/Makefile.build:309: /opt/redpill-lkm/compat/string_compat.o] Error 1
make[2]: *** [Makefile:1229: _module_/opt/redpill-lkm] Error 2
make[2]: Leaving directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
make[1]: *** [Makefile:90: dev-v7] Error 2
make[1]: Leaving directory '/opt/redpill-lkm'
make: *** [Makefile:24: build_redpill_lkm] Error 2
