### ISSUE TITLE
920+会提示没有检测到硬盘，导致无法安装

### ISSUE THREAD

**Issue by sakurawill** [tossp/redpill-tool-chain#101]
920+会提示没有检测到硬盘，导致无法安装

**Comment by tossp** [comment]
自定义驱动树做了吗？

https://github.com/jumkey/redpill-load/blob/develop/redpill-dtb/README.md

**Comment by sakurawill** [comment]
> 

我用的是你生成的920引导哦

**Comment by tossp** [comment]
也是需要自定义驱动树的
