### ISSUE TITLE
3615和3617编译时会报这个错version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by XihongshiFG** [tossp/redpill-tool-chain#102]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)

编译环境是Ubuntu20.04

但是编译dva3221和ds3622xsp不会出现这个错误，可以顺利跑完，其他未测试。

![00001](https://user-images.githubusercontent.com/104178481/164583636-8f1c0b6c-cc13-4cf0-a5d9-932fb2b07e33.png)

网上搜了下这个错误的解决方案，发现对应版本是安装的，后来重新编译GLIBC安装后还是不行
![00002](https://user-images.githubusercontent.com/104178481/164583640-2d59269d-97ca-481e-ab3c-a2403cebaccc.png)
不知道问题在哪，或者大佬推荐下能正常的编译环境。

感谢技术大佬分享！

**Comment by tossp** [comment]
cc #98
