### ISSUE TITLE
unraid 安装918p 提示磁盘格式化错误

### ISSUE THREAD

**Issue by zhudan** [tossp/redpill-tool-chain#103]
unraid 安装918p 提示磁盘格式化错误，这个有什么思路排查么？

**Comment by tossp** [comment]
没有用过 unraid

**Comment by zhudan** [comment]
已经解决，给的vdisk空间太小，给到25G解决，具体要多大未测试

**Comment by wincol1151** [comment]
> 已经解决，给的vdisk空间太小，给到25G解决，具体要多大未测试

只要是虚拟机 pve esxi vm 等等 给定的硬盘必须大于8G    我也有这个问题 后来增加换个更大的虚拟磁盘就可以了
