### ISSUE TITLE
编译ds3615xs_42661时报错

### ISSUE THREAD

**Issue by yhl452493373** [tossp/redpill-tool-chain#104]
```bash
./helper.sh
[#] Checking runtime for required tools... [OK]
[#] Verifying /opt/redpill-load/cache/ds3615xs_42661.pat file... [ERR]
[!] Checksum mismatch - expected e5b708c9340219f657b2eaf6c0fc1c375613c7d4661e185e25bb6deb8aba32d8 but computed 373fe49e5494b4fe68505223212a07e56068687268ae820c76df0566edda11ec

*** Process will exit ***
```
build的时候没问题，auto的时候报上面的错

**Comment by tossp** [comment]
删除ds3615xs_42661.pat

**Comment by lukemin** [comment]
[#] Downloading remote file https://global.download.synology.com/download/DSM/release/7.0.1/42218/DSM_DS3615xs_42218.pat to /opt/redpill-load/cache/extract.tar.gz
######################################################################## 100.0%
[#] Unpacking /opt/redpill-load/cache/extract.tar.gz file to /tmp/synoesp... [OK]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1

**Comment by tossp** [comment]
https://github.com/tossp/redpill-tool-chain/runs/6000194504?check_suite_focus=true

**Comment by lukemin** [comment]
> https://github.com/tossp/redpill-tool-chain/runs/6000194504?check_suite_focus=true
> 
> 所有脚本已经经过测试，请检查本地环境

ds3615xs-7.0.1-42218没问题，ds3615xs_42661不行。

**Comment by lukemin** [comment]
root@instance-20210811-1316:/home/ubuntu/redpill-tool-chain# ./redpill_tool_chain.sh
Usage: ./redpill_tool_chain.sh <action> <platform version>

Actions: build, auto, run, clean, add, del, sn, pat

- build:    Build the toolchain image for the specified platform version.

- auto:     Starts the toolchain container using the previosuly build toolchain image for the specified platform.
            Updates redpill sources and builds the bootloader image automaticaly. Will end the container once done.

- run:      Starts the toolchain container using the previously built toolchain image for the specified platform.
            Interactive Bash terminal.

- clean:    Removes old (=dangling) images and the build cache for a platform version.
            Use ‘all’ as platform version to remove images and build caches for all platform versions.

- add:      To install extension you need to know its index file location and nothing more.
            eg: add 'https://example.com/some-extension/rpext-index.json'

- del:      To remove an already installed extension you need to know its ID.
            eg: del 'example_dev.some_extension'

- sn:       Generates a serial number and mac address for the following platforms
            DS3615xs DS3617xs DS916+ DS918+ DS920+ DS3622xs+ FS6400 DVA3219 DVA3221 DS1621+
            eg: sn ds920p

- pat:      For decoding PAT file. see: https://github.com/tossp/redpill-tool-chain/blob/master/.github/workflows/pat.yml

Available platform versions:
---------------------
ds1621p-7.0.1-42218
ds1621p-7.1.0-42661
ds3615xs-6.2.4-25556
ds3615xs-7.0.1-42218
ds3615xs-7.1.0-42661
ds3617xs-7.0.1-42218
ds3617xs-7.1.0-42661
ds3622xsp-7.0.1-42218
ds3622xsp-7.1.0-42661
ds918p-6.2.4-25556
ds918p-7.0.1-42218
ds918p-7.1.0-42661
ds920p-7.0.1-42218
ds920p-7.1.0-42661
dva3221-7.0.1-42218
dva3221-7.1.0-42661

Custom Extensions:
---------------------
jumkey.acpid2
pocopico.early-telnet
pocopico.r8168
redpill-boot-wait
thethorgroup.boot-wait
thethorgroup.jg.virtio

Check global_settings.json for settings.
root@instance-20210811-1316:/home/ubuntu/redpill-tool-chain# ./redpill_tool_chain.sh auto ds3615xs-7.1.0-42661
Checking if redpill-lkm sources require pull.
  Nothing to do.
Check if redpill-load sources require pull.
  Nothing to do.
Lay back and enjoy the show: Magic is about to happen!
make[1]: Entering directory '/opt/redpill-lkm'
make -C /opt/toolkit_dev-bromolow-7.1.0-42661 M=/opt/redpill-lkm RP_MODULE_TARGET="dev" RP_MODULE_TARGET_VER="7" modules
make[2]: Entering directory '/opt/toolkit_dev-bromolow-7.1.0-42661'
RP-TARGET SPECIFIED AS dev v7
  CC [M]  /opt/redpill-lkm/compat/string_compat.o
  CC [M]  /opt/redpill-lkm/internal/helper/math_helper.o
  CC [M]  /opt/redpill-lkm/internal/helper/memory_helper.o
  CC [M]  /opt/redpill-lkm/internal/helper/symbol_helper.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_toolbox.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_notifier_list.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_notifier.o
  CC [M]  /opt/redpill-lkm/internal/override/override_symbol.o
  CC [M]  /opt/redpill-lkm/internal/override/override_syscall.o
  CC [M]  /opt/redpill-lkm/internal/intercept_execve.o
  CC [M]  /opt/redpill-lkm/internal/call_protected.o
  CC [M]  /opt/redpill-lkm/internal/intercept_driver_register.o
  CC [M]  /opt/redpill-lkm/internal/stealth/sanitize_cmdline.o
  CC [M]  /opt/redpill-lkm/internal/stealth.o
  CC [M]  /opt/redpill-lkm/internal/virtual_pci.o
  CC [M]  /opt/redpill-lkm/internal/uart/uart_swapper.o
  CC [M]  /opt/redpill-lkm/internal/uart/vuart_virtual_irq.o
  CC [M]  /opt/redpill-lkm/internal/uart/virtual_uart.o
  CC [M]  /opt/redpill-lkm/internal/ioscheduler_fixer.o
  CC [M]  /opt/redpill-lkm/config/cmdline_delegate.o
  CC [M]  /opt/redpill-lkm/config/runtime_config.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/boot_shim_base.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/usb_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.o
In file included from /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.c:46:0:
/opt/redpill-lkm/compat/toolkit/include/../drivers/usb/storage/usb.h:50:2: warning: #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit" [-Wcpp]
 #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit"
  ^
  CC [M]  /opt/redpill-lkm/shim/boot_dev/native_sata_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_device_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/smart_shim.o
/opt/redpill-lkm/shim/storage/smart_shim.c: In function 'populate_ata_id':
/opt/redpill-lkm/shim/storage/smart_shim.c:287:5: warning: ignoring return value of 'strscpy', declared with attribute warn_unused_result [-Wunused-result]
     strscpy(disk_serial, disk_name, DISK_NAME_LEN > 20 ? 20 : DISK_NAME_LEN);
     ^
  CC [M]  /opt/redpill-lkm/shim/storage/sata_port_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwcap_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwmon_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/rtc_proxy.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_shims_collection.o
  CC [M]  /opt/redpill-lkm/shim/bios_shim.o
  CC [M]  /opt/redpill-lkm/shim/block_fw_update_shim.o
  CC [M]  /opt/redpill-lkm/shim/disable_exectutables.o
  CC [M]  /opt/redpill-lkm/shim/pci_shim.o
  CC [M]  /opt/redpill-lkm/shim/pmu_shim.o
  CC [M]  /opt/redpill-lkm/shim/uart_fixer.o
  CC [M]  /opt/redpill-lkm/redpill_main.o
  LD [M]  /opt/redpill-lkm/redpill.o
  Building modules, stage 2.
RP-TARGET SPECIFIED AS dev v7
  MODPOST 1 modules
  CC      /opt/redpill-lkm/redpill.mod.o
  LD [M]  /opt/redpill-lkm/redpill.ko
make[2]: Leaving directory '/opt/toolkit_dev-bromolow-7.1.0-42661'
make[1]: Leaving directory '/opt/redpill-lkm'
#############################################
filename:       /opt/redpill-lkm/redpill.ko
license:        GPL
version:        v0.5-at-2022_04_27-00_55_25
author:         TTG
retpoline:      Y
srcversion:     E29E1E6BA8F2820752BC2F6
depends:        
vermagic:       3.10.108 SMP mod_unload 
#############################################
Using user_config.json:
{
    "extra_cmdline": {
        "pid": "0x5***",
        "vid": "0x0***",
        "sn": "****LWN0*****",
        "mac1": "00113*******",
        "mac2": "00113*******",
        "mac3": "00113*******",
        "netif_num": "4"
    },
    "synoinfo": {
        "maxlanport": "4",
        "myds_region_api_base_url": "https://account.synology.com/",
        "rss_server": "http://update.synology.com/autoupdate/genRSS.php",
        "rss_server_ssl": "https://update.synology.com/autoupdate/genRSS.php",
        "updateurl": "http://www.synology.com/",
        "small_info_path": "https://update.synology.com/smallupdate"
    },
    "ramdisk_copy": {},
    "extensions": []
}

#############################################
./helper.sh
[#] Checking runtime for required tools... [OK]
[#] Verifying /opt/redpill-load/cache/ds3615xs_42661.pat file... [OK]
[#] File /opt/redpill-load/cache/ds3615xs_42661.pat, Decryption required
[#] Test encryption pat results 1

[#] Unpacking /opt/redpill-load/cache/extract.tar.gz file to /tmp/synoesp... [OK]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1
root@instance-20210811-1316:/home/ubuntu/redpill-tool-chain#

**Comment by tossp** [comment]
cc #94

**Comment by yhl452493373** [comment]
自己服务器上编译老过不了。。还是fork一个，改下配置，直接跑action。。。
