### ISSUE TITLE
PVE  安装 ds918 7.1时没有问题，当我直通sata控制器，就会出现 硬盘错误 sata口被禁用。

### ISSUE THREAD

**Issue by eason666888** [tossp/redpill-tool-chain#106]
调整 SataPortMap，SataPortMap  也不管用，之前7.01一样安装办法，没有这个问题。。
![image](https://user-images.githubusercontent.com/103944546/164994771-5ee0e4b5-b9ab-4faf-ae9e-900d527f0053.png)

**Comment by tossp** [comment]
好像有人反馈过这个错误，最终反馈一下子没找到，记忆中是磁盘给小了

**Comment by tossp** [comment]
#103
