### ISSUE TITLE
./redpill_tool_chain.sh pat 命令作用是什么？

### ISSUE THREAD

**Issue by Toonter** [tossp/redpill-tool-chain#108]
Actions 自动打包时 ds361X 的 42661 版本有一步**预处理PAT**包含 `./redpill_tool_chain.sh pat` 的处理，readme 中只提到这个命令是对 pat 做 decode，workflows 目录下也没有找到 pat.yml。

状况：
硬盘已使用其他 3615 引导顺利安装系统，但因为有瑕疵且原因不明（ESXi 下 Photos WEB 只有主用户可以登录，新建的用户即使赋予管理员权限也无法 WEB 登录，物理机正常），所以尝试自己编译引导。修改 Actions 额外添加 e1000e、r8125、vmxnet3 三个网卡驱动，打包的 ds3615 引导在 ESXi 下可以顺利开机并引导系统，可以用群晖搜索工具搜索到，可以 SSH 登录，但 WEB 访问群晖登录页面虚拟机就关机。

问题：
想知道是否与 `./redpill_tool_chain.sh pat` 命令有关系？ds361X 的 42661 需要在安装系统的时候选择预处理过的 PAT 文件吗？

**Comment by tossp** [comment]
确实只是做解包，再重新打包pat，让后续命令可以正常提取文件

**Comment by Toonter** [comment]
看了一下 [这里](https://github.com/tossp/redpill-tool-chain/issues/94#issuecomment-1095943785) 提到的3615 编译流程，看来跟这个没有关系，只能继续找别的问题了。
