### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by thestreetdj** [tossp/redpill-tool-chain#11]
![화면 캡처 2021-10-21 000311](https://user-images.githubusercontent.com/66782791/138119282-9145e6da-9f6e-489f-bb3c-b81a90d55139.png)

**Comment by tossp** [comment]
I don't know what you have modified. This compilation process has been verified. Please ensure that your configuration file has been verified

cc https://github.com/tossp/redpill-tool-chain/runs/3886905022?check_suite_focus=true

**Comment by thestreetdj** [comment]
![화면 캡처 2021-10-21 104727](https://user-images.githubusercontent.com/66782791/138197117-93594028-79c7-471f-9db1-ca2747f5e60a.png)
The same is true of deleting all folders and working after receiving a new git clone.
