### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by JoeyChoGG** [tossp/redpill-tool-chain#111]
it occurred when I run 'auto' command

[!] Extension is already added (index exists at /opt/redpill-load/custom/extensions/redpill-boot-wait/redpill-boot-wait.json). For more info use "ext-manager.sh info redpill-boot-wait"

*** Process will exit ***
[!] Failed to install redpill.bootwait bundled extension - see errors above

*** Process will exit ***

how can I fix this.

**Comment by fanlinchong** [comment]
删掉custom/extensions 重新编译就可以了
