### ISSUE TITLE
ds918p-7.1.0引导编译安装后web访问会自动关机

### ISSUE THREAD

**Issue by XXPXXPXXP** [tossp/redpill-tool-chain#112]
求助大佬，正常编译ds918+ 7.1.0引导后可以启动，但安装完成后通过web访问就会提示“抱歉，你访问的页面不存在”，同时系统会在几秒后关机。请问这种情况该怎么排查问题。
驱动只添加了redpill-boot-wait

**Comment by tossp** [comment]
实际情况比较复杂，无法判断原因

我在b150主板实体安装和pve安装正常

先进串口去看dmesg吧

**Comment by Lasx** [comment]
不止你一个哦，我3615 、3617都是这个问题

**Comment by fanlinchong** [comment]
我也是同样的问题

**Comment by tossp** [comment]
这边只是引导生成工具，可能再xpenology的ddr区会有有效的帮助

**Comment by tossp** [comment]
好像你们都是本地生成吧，试试在线生成呢

**Comment by tossp** [comment]
这四个基础扩展都装了吗？刚刚请热心网友测试了一下，这四个没装全会出现你描述的问题

```
./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json
./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-acpid.json
./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-virtio.json
./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-misc.json
```

**Comment by Lasx** [comment]
> 这四个基础扩展都装了吗？刚刚请热心网友测试了一下，这四个没装全会出现你描述的问题
> 
> ```
> ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json
> ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-acpid.json
> ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-virtio.json
> ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-misc.json
> ```

我好像只加装了一个虚拟机网卡的。这几个好像都没装。

**Comment by Lasx** [comment]
试过添加基础扩展了，编译出来的提示无法安装。。

**Comment by XXPXXPXXP** [comment]
刚试完，全部安装后会出现无限循环安装。并且编译7.0.1版本后直接安装可以正常启动和web访问，但7.1.0的版本就会出现web访问后就自动关机的情况

**Comment by Lasx** [comment]
我试着用github action编译，编译结果可以运行了，不报错了。

**Comment by tcbt999** [comment]
这个问题，已经困恼我很久，终于找到解决方案，我的物理机器如果先按照 ds3615xs,ds3622xs,7.1版本，能安装成功，但是重启后，访问网页，就会自动关机。我的解决方法：1、先编译7.0.1.42281，用优盘启动，成功安装，配置好磁盘；2、编译7.1.42661，刷入优盘，重启后，再安装7.1，保留文件。3、重启后，等群晖上线，应该能进入桌面。4、还有那个电源关闭补丁，先不装。
