### ISSUE TITLE
大佬，报错显示不全，还不能换行。

### ISSUE THREAD

**Issue by sjkhsl** [tossp/redpill-tool-chain#113]
报错显示不全，这个报错只显示一行，拉到最大了，还是显示不全。

=> ERROR [stage-1  2/10] RUN apt-get update &&     apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod &&     rm -rf /var/lib/apt/lists/* /tmp/* &&     curl --progress-bar --output /usr/bin/jq --location https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +

**Comment by tcbt999** [comment]
编译环境2个命令

**Comment by tossp** [comment]
抱歉，不清楚报错原因
