### ISSUE TITLE
部分平台42661版本的pat文件被官方移动导致报403错误，无法获取pat

### ISSUE THREAD

**Issue by xujianjie1213** [tossp/redpill-tool-chain#114]
![image](https://user-images.githubusercontent.com/35050408/166877703-44ed4ea6-54ef-48b7-8bf3-3ec0648cd6e3.png)
3617编译正常，3615报错如图

**Comment by tossp** [comment]
群晖调整了安装包路径需要等待依赖上游升级
或者自行调整

**Comment by xujianjie1213** [comment]
是把7.1/42661/ 这里改成7.1/42661-1 这样么？

**Comment by colinhd8** [comment]
不只路径调整了，还有sha256也变了。不过这两个都改了后，最终在untar的时候报不是压缩包，看来还有地方没改全。

**Comment by tossp** [comment]
需要重做 redpill-load 库里面pat文件的指向，欢迎提交PR

**Comment by tossp** [comment]
上游已修复
