### ISSUE TITLE
运行auto 918+一直弹这个报错，怎么解决啊

### ISSUE THREAD

**Issue by starskytale** [tossp/redpill-tool-chain#115]
[!] Failed to download https://raw.githubusercontent.com/tossp/rp-ext/master/redpill-boot-wait/rpext-index.json to /opt/redpill-load/custom/extensions/_new_ext_index.tmp_json

*** Process will exit ***

[!] Failed to add "https://raw.githubusercontent.com/tossp/rp-ext/master/redpill-boot-wait/rpext-index.json" as an extension:

,

*** Process will exit ***
[!] Failed to install thethorgroup.boot-wait bundled extension - see errors above

*** Process will exit ***

**Comment by tossp** [comment]
翻墙或者在线编译
