### ISSUE TITLE
链接403了

### ISSUE THREAD

**Issue by ZisenNie** [tossp/redpill-tool-chain#119]
./helper.sh
[#] Checking runtime for required tools... [OK]
[#] Downloading remote file https://global.download.synology.com/download/DSM/release/7.1/42661/DSM_DS918%2B_42661.pat to /opt/redpill-load/cache/ds918p_42661.pat
-=O#-   #     #        #                                                                                                                                                    
curl: (22) The requested URL returned error: 403 
include/file.sh: line 298: 3: unbound variable
make: *** [Makefile:33: build_redpill_load] Error 1

**Comment by tossp** [comment]
cc #114 
重复
