### ISSUE TITLE
自行添加扩展驱动Actions编译通不过

### ISSUE THREAD

**Issue by blankhub** [tossp/redpill-tool-chain#121]
大佬，我Fork了一份后自己添加了tg3网卡驱动，并从pocopico那边添加了相应的json，编译通不过，卡在自己添加的驱动，格式我都是按照您的json格式的，不知道哪里出错了，大佬可以添加一份tg3网卡的拓展驱动吗？

**Comment by tcbt999** [comment]
这个错误，我知道怎么处理，格式虽然对，但是，要转换成https://raw.guthubusercontent.com开头的样子，实际就是你点击打开那个json文件，里面的，复制以这个样子开头的那一行，就行了

**Comment by tossp** [comment]
https://github.com/blankhub/redpill-tool-chain/blob/016ecb4ae0fec0be1f5297d39de043eed6311374/extensions/pocopico-tg3.json#L3


这个要换你自己仓库的地址啊，我这边并没有这个文件

`https://raw.githubusercontent.com/blankhub/redpill-tool-chain/master/extensions/pocopico-tg3.json`

**Comment by blankhub** [comment]
好的，我试试。我换我仓库的地址了的，只是我不懂存在真假json的问题，不是raw的json链接，打开会是一个网页，不是真实的json，我尝试一下，谢谢各位解答

**Comment by blankhub** [comment]
跑通了跑通了😊😊😊，谢谢各位大神，授人以渔🎣🐟
