### ISSUE TITLE
ds 3615xs compile

### ISSUE THREAD

**Issue by lhywc** [tossp/redpill-tool-chain#122]
[#] Unpacking /opt/redpill-load/cache/extract.tar.gz file to /tmp/synoesp... [OK]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed

**Comment by tossp** [comment]
cc https://github.com/tossp/redpill-tool-chain/blob/54da8ad2e4a27bd9d23bc33274a83d9cf979b0db/.github/workflows/test.yml#L137

**Comment by lhywc** [comment]
thk

**Comment by lhywc** [comment]
成都哪儿的
大哥

**Comment by lhywc** [comment]
今天能不能修复完成，谢谢！

**Comment by tossp** [comment]
一直是可用的啊

https://github.com/tossp/redpill-tool-chain/actions/runs/2326644761

**Comment by lhywc** [comment]
我今天在编译的时候还是在报这个错，我再来试试

**Comment by tossp** [comment]
你直接在线编译吧
