### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by lhywc** [tossp/redpill-tool-chain#123]
/opt/redpill-lkm/config/cmdline_delegate.c: In function 'extract_config_from_cmdline':
/opt/redpill-lkm/config/cmdline_delegate.c:413:74: warning: value computed is not used [-Wunused-value]
         extract_netif_macs(config->macs, single_param_chunk)             ||
                                                                          ^~
  CC [M]  /opt/redpill-lkm/config/runtime_config.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/boot_shim_base.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/usb_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.o
In file included from /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.c:46:
/opt/redpill-lkm/compat/toolkit/include/../drivers/usb/storage/usb.h:50:2: warning: #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit" [-Wcpp]
 #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit"
  ^~~~~~~
  CC [M]  /opt/redpill-lkm/shim/boot_dev/native_sata_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_device_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/smart_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/sata_port_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwcap_shim.o
/opt/redpill-lkm/shim/bios/bios_hwcap_shim.c: In function 'GetHwCapability_shim':
/opt/redpill-lkm/shim/bios/bios_hwcap_shim.c:64:17: warning: unused variable 'ovs_fout' [-Wunused-variable]
             int ovs_fout = call_overridden_symbol(org_fout, GetHwCapability_ovs, cap);
                 ^~~~~~~~

**Comment by tossp** [comment]
cc

https://github.com/tossp/redpill-tool-chain/blob/0bbb54a2b56e2f277aeab7b31ffd508c400a808f/.github/workflows/test.yml#L140-L144

**Comment by lhywc** [comment]
ojbk再试试

**Comment by lhywc** [comment]
哦，忘记第三步了

**Comment by lhywc** [comment]
成功
