### ISSUE TITLE
无法重启

### ISSUE THREAD

**Issue by yfyhboy** [tossp/redpill-tool-chain#139]
大神好，感谢你提供的脚本！
现在有点小问题。
我在PVE上安装了3622 7.1版本，发现在网页上操作重启会卡死。
串口打印信息如下：
[ 129.761389] reboot: Restarting system
[ 129.761973] reboot: machine restart
[ 129.763592] ACPI MEMORY or I/O RESET_REG.

CPU: i5-7500
board: asus B250M-plus
主机: PVE 7.2-3
虚拟机: ds3622xsp 7.1.0-42661
扩展驱动: redpill-boot-wait, redpill-acpid, redpill-virtio, redpill-misc

网上查了一下说是acpid的bug，但没有详细说明原因，给出的方案是禁用acpid。。。请问这个问题有解决方案吗？还是说就不能安装acpid驱动了？
https://www.thegeekdiary.com/centos-rhel-8-acpi-memory-or-i-o-reset_reg-server-hung-after-reboot/

**Comment by tossp** [comment]
没法复现问题，建议到ddr社区获取更多支持

 asus B150M-plus 正常
