### ISSUE TITLE
918+ 7.0.1-42218引导安装系统重启后进入系统恢复循环

### ISSUE THREAD

**Issue by fromthink** [tossp/redpill-tool-chain#143]
系统提示为可恢复，恢复后重启还是可恢复状态。7.0-41890和7.1.0-42661都没有这个问题

**Comment by yfyhboy** [comment]
断外网安装试试

**Comment by fromthink** [comment]
非常感谢，可以了！似乎是群晖在安装过程中自动升级了？

**Comment by fromthink** [comment]
42218 update 4会造成进入可恢复状态

**Comment by tcbt999** [comment]
不能升级到42218 update 4

**Comment by xieqinb** [comment]
今天我pve 全新安装，几个版本试过都出现你这个情况了

**Comment by lhywc** [comment]
这个问题应该去红丸的厂库去

**Comment by xu373297464** [comment]
用新版本试试吧 我昨天编译的 实体机 虚拟机都没有问题 不过7.0.1不要用up4
