### ISSUE TITLE
我在运行 auto的时候 出现这个错误 我很无奈 

### ISSUE THREAD

**Issue by wincol1151** [tossp/redpill-tool-chain#149]
Using user_config.json:
{
    "extra_cmdline": {
        "pid": "0x0951",
        "vid": "0x1666",
        "sn": "1230ODN025150",
        "mac1": "001132EA9282"
        
},
    "synoinfo": {},
    "ramdisk_copy": {},
    "extensions": []
}
#############################################
./helper.sh
[#] Checking runtime for required tools... [OK]
[#] Verifying /opt/redpill-load/cache/ds3617xs_42661.pat file... [OK]
[#] File /opt/redpill-load/cache/ds3617xs_42661.pat, Decryption required
[#] Test encryption pat results 1

[#] Unpacking /opt/redpill-load/cache/extract.tar.gz file to /tmp/synoesp... [OK]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1

以上是我在运行 auto 命令时出现的问题  我现在 GLIBC_版本是2.31   不知道现在该如何解决  挺困惑的

**Comment by wincol1151** [comment]
补充： 编译的版本 ds3617xs-7.1-42661

**Comment by tossp** [comment]
cc https://github.com/tossp/redpill-tool-chain/blob/0bbb54a2b56e2f277aeab7b31ffd508c400a808f/.github/workflows/test.yml#L137-L144

**Comment by wincol1151** [comment]
好的 多谢了

**Comment by leavr** [comment]
> 好的 多谢了

老兄，解决了吗？

**Comment by wincol1151** [comment]
> > 好的 多谢了
> 
> 老兄，解决了吗？

没有  我猜还是编译环境没弄好 最后 不弄了  改成在线编译了 非常好用    现在3615 7.1  已经成功在vm 和威联通的虚拟机跑起来了 等最后在实体机在试试   大神的工具非常好用

**Comment by wanlunglau** [comment]
同样的错误，编译的版本也是ds3617xs-7.1-42661，求解，作者回复一个cc是什么意思？完全不懂啊。。。

**Comment by leavr** [comment]
> 同样的错误，编译的版本也是ds3617xs-7.1-42661，求解，作者回复一个cc是什么意思？完全不懂啊。。。

本地编译问题太多了，建议还是使用github的云编译算了

**Comment by xu373297464** [comment]
建议云编译 嗖嗖快

**Comment by 924060929** [comment]
> 同样的错误，编译的版本也是ds3617xs-7.1-42661，求解，作者回复一个cc是什么意思？完全不懂啊。。。

tossp的意思是如果是`ds361....42661`的版本，就要把global_config.json文件中的`debian:8-slim`这个老版本的docker镜像改为`debian:10-slim`，用新版本先去build和pat，然后再改回`debian:8-slim`去build

**Comment by galaxy-eye** [comment]
> 

老哥你加了哪些驱动，我用的kvm虚拟机，我网卡是e1000的，只加了e1000网卡驱动，然后云编译出来识别不到硬盘
