### ISSUE TITLE
又来叨扰了  昨天编译的 ds3617-7.1-42661 无限重装

### ISSUE THREAD

**Issue by wincol1151** [tossp/redpill-tool-chain#155]
昨天编译的ds3617-7.1-42661 可以找到IP 但是安装最后总是无限循环 。总是最后出现安装错误 很奇怪

**Comment by tossp** [comment]
#143

**Comment by jinlife** [comment]
Loader 需要升级，现在的loader默认会装最新的update，但是前几天出来的update 2导致装好了也用不了。

**Comment by wincol1151** [comment]
好的 明白 我去试试
