### ISSUE TITLE
是否考虑支持DSM 7.1.0-42661 Update 2

### ISSUE THREAD

**Issue by CCA2878** [tossp/redpill-tool-chain#163]
如题。

**Comment by tossp** [comment]
欢迎提交PR

**Comment by miniers** [comment]
ds918p-7.0.1-42218

**Comment by OiCkilL** [comment]
> ds918p-7.0.1-42218 这个编译出来是支持 DSM 7.1.0-42661 Update 2 的

并不行，通过socket看引导一半会进单用户模式

**Comment by wincol1151** [comment]
臣复议

**Comment by xu373297464** [comment]
昨天刚编译的j4125 4盘位
ds918p-7.0.1-42218 这个可以联网自动升级到 7.1up2

**Comment by xiaoliu0802** [comment]
构建镜像的时候总是提示没有指定，Platform version ds918p-7.1.0-42261 not specified in global_config.json，是不支持42661吗，42218没问题

**Comment by iTQuanNet** [comment]
> 构建镜像的时候总是提示没有指定，Platform version ds918p-7.1.0-42261 not specified in global_config.json，是不支持42661吗，42218没问题

没仔细看说明?
`1、复制 sample_user_config.json 为 ds3615xs_user_config.json 或者 ds918p_user_config.json`

**Comment by jun1021CN** [comment]
make: *** [Makefile:33: build_redpill_load] Error 1
请问这是什么情况

**Comment by manyzhu** [comment]
=> ERROR [stage-1  2/10] RUN apt-get update &&     apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod &&    请问哪里出错了

**Comment by xiaoliu0802** [comment]
我知道啊，ds918p_user_config.json编译42661和42218不都是同一个文件名么，42661就会提示那个问题> 
> 
> > 构建镜像的时候总是提示没有指定，Platform version ds918p-7.1.0-42261 not specified in global_config.json，是不支持42661吗，42218没问题
> 
> 
> 
> 没仔细看说明?
> 
> `1、复制 sample_user_config.json 为 ds3615xs_user_config.json 或者 ds918p_user_config.json`
