### ISSUE TITLE
安装包已损毁

### ISSUE THREAD

**Issue by caopeiyu1998** [tossp/redpill-tool-chain#180]
我在安装ds3617xs-7.1.0-42661时候，进度到56%时候出现安装包损毁，换U盘，断网装都一样，请问是什么原因，谢谢

**Comment by tossp** [comment]
额，，，我也不清楚哎，可以去ddr寻求更多帮助

**Comment by caopeiyu1998** [comment]
>

**Comment by caopeiyu1998** [comment]
> 额，，，我也不清楚哎，可以去ddr寻求更多帮助


我搜过这个问题，说是vid和pid不对，请问我这样编译格式对吗
 # 调整VID和PID
          sed -i -e 's/0x0001/0x88AA/g' -e 's/0x46f4/0x88AA/g' ${{matrix.platform}}_user_config.json
          # 调整SN和MAC,最好使用 actions secrets 引入,SN应该是固定值不应该每次生成
          sn=`./redpill_tool_chain.sh sn ${{matrix.platform}} | grep 'Serial Number' | awk '{print $3}'`
          sed -i -e "s/1234XXX123/${sn:="1130LWN123456"}/g" -e 's/XXYYXXYYXXYY/0011323D47F7/g' ${{matrix.platform}}_user_config.json

**Comment by tossp** [comment]
```
sn=`./redpill_tool_chain.sh sn ${{matrix.platform}} | grep 'Serial Number' | awk '{print $3}'`
```
改为，上面的意思是根据平台生成sn,`${sn:="1130LWN123456"}`是在上面生成失败了，使用`1130LWN123456`
···
sn='你的sn'
···

**Comment by caopeiyu1998** [comment]
> ```shell
> sn=`./redpill_tool_chain.sh sn ${{matrix.platform}} | grep 'Serial Number' | awk '{print $3}'`
> ```
> 
> 改为，上面的意思是根据平台生成sn,`${sn:="1130LWN123456"}`是在上面生成失败了，使用`1130LWN123456`
> 
> ```shell
> sn='你的sn'
> ```
> 
> btw: `0x88AA`你买的tank的启动盘？

我fork 的你的代码啊，原代码就是这个

**Comment by uwtom** [comment]
> ```shell
> ```shell
> sn=`./redpill_tool_chain.sh sn ${{matrix.platform}} | grep 'Serial Number' | awk '{print $3}'`
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 改为，上面的意思是根据平台生成sn,${sn:="1130LWN123456"}是在上面生成失败了，使用1130LWN123456
> ```shell
> sn='你的sn'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> btw: 0x88AA你买的tank的启动盘？
> 
> 我fork 的你的代码啊，原代码就是这个
> ```

pid和vid要改为你的U盘对应的pid和vid才能正确引导，即使你在这编译时什么都不改，生成引导下载后你也要修改grub.cfg里的信息才能正确引导呀

**Comment by caopeiyu1998** [comment]
> 

我改过了，现在就是玄学吧，3617装损毁，3615-7.01可以正常装了用，7.1装了无限重启，我就凑活用吧

**Comment by uwtom** [comment]
> > 
> 
> 
> 
> 我改过了，现在就是玄学吧，3617装损毁，3615-7.01可以正常装了用，7.1装了无限重启，我就凑活用吧

我918+ 7.1一点问题都没有……这真的就很玄学了

**Comment by fenghuan1994** [comment]
7.1要断网安装，好像现在官网没有7.1-42661初始版本下载了，最低也是update1

**Comment by uwtom** [comment]
https://archive.synology.cn/download/Os/DSM
![image](https://user-images.githubusercontent.com/43116646/180738702-043f78dd-602a-4fd5-b098-bc9a90fcf98c.jpeg)

**Comment by uwtom** [comment]
刚看了一下，7.1-42261只剩下虚拟机安装文件了……
https://archive.synology.cn/download/Os/DSM

**Comment by caopeiyu1998** [comment]
> 刚看了一下，7.1-42261只剩下虚拟机安装文件了…… https://archive.synology.cn/download/Os/DSM

恐怕群晖已经意识到这个问题，所以把包撤了吧

**Comment by Mikesco3** [comment]
I'm having the error when trying to `redpill_tool_chain.sh auto ds3615xs-7.1.0-42661` <br>
```
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1

```

**Comment by tossp** [comment]
> I'm having the error when trying to `redpill_tool_chain.sh auto ds3615xs-7.1.0-42661`
> 
> ```
> [#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
> /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
> [ERR]
> [#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
> [!] Failed to unpack tar
> 
> /bin/tar: /tmp/pat/: Cannot open: No such file or directory
> /bin/tar: Error is not recoverable: exiting now
> 
> *** Process will exit ***
> Makefile:30: recipe for target 'build_redpill_load' failed
> make: *** [build_redpill_load] Error 1
> ```

https://github.com/tossp/redpill-tool-chain/issues/149#issuecomment-1141642889

**Comment by galaxy-eye** [comment]
现在还有途径下载到DSM_DS3617xs_42661原版吗
