### ISSUE TITLE
ERROR [internal] load metadata for docker.io/library/debian:8-slim

### ISSUE THREAD

**Issue by palislau** [tossp/redpill-tool-chain#185]
小白求助，build时出现以下报错，怎么处理:

[+] Building 2.0s (3/3) FINISHED                                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 32B                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                  0.1s
 => => transferring context: 2B                                                                                                                                    0.1s
 => ERROR [internal] load metadata for docker.io/library/debian:8-slim                                                                                             1.8s
------
 > [internal] load metadata for docker.io/library/debian:8-slim:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:b9b0e7354098cbd534861d7532c082fb81cdb4d893303ba1f322f52c9e583cd2: not found

**Comment by tossp** [comment]
在线编译

**Comment by palislau** [comment]
> 在线编译

可以稍微说明白点，怎么在线编译吗？
