### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by hnhyqdzxl** [tossp/redpill-tool-chain#186]
#=O#-  #     #
curl: (7) Couldn't connect to server
[!] Failed to download https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json to /opt/redpill-load/custom/extensions/_new_ext_index.tmp_json

*** Process will exit ***

[!] Failed to add "https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json" as an extension:

,

*** Process will exit ***
[!] Failed to install redpill.bootwait bundled extension - see errors above

*** Process will exit ***

**Comment by tossp** [comment]
看着像没翻墙的样子，，，直接云编译吧
