### ISSUE TITLE
使用Actions云编译ds920p-7.1.0-42661出错

### ISSUE THREAD

**Issue by chriskong5155** [tossp/redpill-tool-chain#190]
使用Actions云编译ds920p-7.1.0-42661时，到准备构建环境步骤提示出错了，后来再试编译918+也是一样的错误，请问一下是什么问题？

Run ./redpill_tool_chain.sh build ds920p-7.1.0-42661
/home/runner/work/_temp/1b57bde9-a793-46d5-9154-264a7bdc12d9.sh: line 1: ./redpill_tool_chain.sh: Permission denied
Error: Process completed with exit code 126.

Run ./redpill_tool_chain.sh build ds918p-7.1.0-42661
/home/runner/work/_temp/9620f91a-0a5c-40ce-96e1-91a5fceba7d3.sh: line 1: ./redpill_tool_chain.sh: Permission denied
Error: Process completed with exit code 126.

**Comment by tossp** [comment]
你直接fork过去，不要自己去传文件
