### ISSUE TITLE
编译ds918p_25556镜像时生成的是MBR分区镜像

### ISSUE THREAD

**Issue by phoenixxie0** [tossp/redpill-tool-chain#227]
编译ds918p_25556镜像时生成的是MBR分区镜像，并不是GUID分区表的镜像，无法用UEFI启动

**Comment by tossp** [comment]
正常使用中

**Comment by phoenixxie0** [comment]
ds918p_6.2.4_25556的引导使用MBR模式引导能安装了，但是很奇怪无法识别显卡。显卡是I3 8100T-UHD630

**Comment by tossp** [comment]
显卡问题，可以在ddr中获取更多帮助
