### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by windsorcerer** [tossp/redpill-tool-chain#23]
Build 没问题 log如下：
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master# ./redpill_tool_chain.sh build bromolow-7.0.1-42218
[+] Building 2.4s (15/15) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 38B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/debian:8-slim                                                   2.2s
 => [stage-1 1/9] FROM docker.io/library/debian:8-slim@sha256:b9b0e7354098cbd534861d7532c082fb81cdb4d893303ba1f32  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 180B                                                                                  0.0s
 => CACHED [stage-1 2/9] RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak &&     sed  -i "s/archive.ubuntu.  0.0s
 => CACHED [stage-1 3/9] RUN git clone https://github.com/RedPill-TTG/redpill-lkm.git  -b master  /opt/redpill-lk  0.0s
 => CACHED [extract 2/2] ADD downloads/ds.bromolow-7.0.dev.txz /                                                   0.0s
 => CACHED [stage-1 4/9] COPY --from=extract /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/  0.0s
 => CACHED [stage-1 5/9] RUN if [ "apollolake" = "bromolow" ]; then echo '+' > /opt/toolkit_dev-bromolow-7.0.1-42  0.0s
 => CACHED [stage-1 6/9] WORKDIR /opt                                                                              0.0s
 => CACHED [stage-1 7/9] COPY Makefile /opt/                                                                       0.0s
 => CACHED [stage-1 8/9] COPY entrypoint.sh /entrypoint.sh                                                         0.0s
 => CACHED [stage-1 9/9] RUN chmod +x /entrypoint.sh                                                               0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:24e497c121e2bd886b90a8e52712a1a8dcfb29005d37218e0effed303b5944f8                       0.0s
 => => naming to docker.io/library/redpill-tool-chain:bromolow-7.0.1-42218                                         0.0s
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master#
/////////////////////////////////////////////////////////////////////////////////////////////////////////////
auto就有问题了：log如下
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master# ./redpill_tool_chain.sh auto bromolow-7.0.1-42218
Checking if redpill-lkm sources require pull.
  Nothing to do.
Check if redpill-load sources require pull.
  Nothing to do.
Lay back and enjoy the show: Magic is about to happen!
make[1]: Entering directory '/opt/redpill-lkm'
make -C /opt/toolkit_dev-bromolow-7.0.1-42218 M=/opt/redpill-lkm RP_MODULE_TARGET="dev" RP_MODULE_TARGET_VER="7" modules
make[2]: Entering directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
RP-TARGET SPECIFIED AS dev v7
  CC [M]  /opt/redpill-lkm/compat/string_compat.o
  CC [M]  /opt/redpill-lkm/internal/helper/math_helper.o
  CC [M]  /opt/redpill-lkm/internal/helper/memory_helper.o
  CC [M]  /opt/redpill-lkm/internal/helper/symbol_helper.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_toolbox.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_notifier_list.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_notifier.o
  CC [M]  /opt/redpill-lkm/internal/override/override_symbol.o
  CC [M]  /opt/redpill-lkm/internal/override/override_syscall.o
  CC [M]  /opt/redpill-lkm/internal/intercept_execve.o
  CC [M]  /opt/redpill-lkm/internal/call_protected.o
  CC [M]  /opt/redpill-lkm/internal/intercept_driver_register.o
  CC [M]  /opt/redpill-lkm/internal/stealth/sanitize_cmdline.o
  CC [M]  /opt/redpill-lkm/internal/stealth.o
  CC [M]  /opt/redpill-lkm/internal/virtual_pci.o
  CC [M]  /opt/redpill-lkm/internal/uart/uart_swapper.o
  CC [M]  /opt/redpill-lkm/internal/uart/vuart_virtual_irq.o
  CC [M]  /opt/redpill-lkm/internal/uart/virtual_uart.o
  CC [M]  /opt/redpill-lkm/internal/ioscheduler_fixer.o
  CC [M]  /opt/redpill-lkm/config/cmdline_delegate.o
  CC [M]  /opt/redpill-lkm/config/runtime_config.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/boot_shim_base.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/usb_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.o
In file included from /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.c:46:0:
/opt/redpill-lkm/compat/toolkit/include/../drivers/usb/storage/usb.h:50:2: warning: #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit" [-Wcpp]
 #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit"
  ^
  CC [M]  /opt/redpill-lkm/shim/boot_dev/native_sata_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_device_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/smart_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/sata_port_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwcap_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwmon_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/rtc_proxy.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_shims_collection.o
  CC [M]  /opt/redpill-lkm/shim/bios_shim.o
  CC [M]  /opt/redpill-lkm/shim/block_fw_update_shim.o
  CC [M]  /opt/redpill-lkm/shim/disable_exectutables.o
  CC [M]  /opt/redpill-lkm/shim/pci_shim.o
  CC [M]  /opt/redpill-lkm/shim/pmu_shim.o
  CC [M]  /opt/redpill-lkm/shim/uart_fixer.o
  CC [M]  /opt/redpill-lkm/redpill_main.o
  LD [M]  /opt/redpill-lkm/redpill.o
  Building modules, stage 2.
RP-TARGET SPECIFIED AS dev v7
  MODPOST 1 modules
  CC      /opt/redpill-lkm/redpill.mod.o
  LD [M]  /opt/redpill-lkm/redpill.ko
make[2]: Leaving directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
make[1]: Leaving directory '/opt/redpill-lkm'
#############################################
filename:       /opt/redpill-lkm/redpill.ko
license:        GPL
version:        v0.5-at-2021_11_08-09_24_08
author:         TTG
retpoline:      Y
srcversion:     9D5817BD80754EFE921A0AC
depends:
vermagic:       3.10.108 SMP mod_unload
#############################################
**Using user_config.json:
cat: /opt/redpill-load/user_config.json: Is a directory
Makefile:29: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1**
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master#
//////////////////////////////////////////////////////////////////////////////////////////////////////////////
我进入Docker查看确实变成目录了。如下
root@redpill-tool-chain:/opt# ls -la /opt/redpill-load/
total 172
drwxr-xr-x 1 root root  4096 Nov  8 09:07 .
drwxr-xr-x 1 root root  4096 Nov  8 09:05 ..
drwxr-xr-x 8 root root  4096 Nov  8 09:05 .git
-rw-r--r-- 1 root root   181 Nov  8 09:05 .gitignore
-rw-r--r-- 1 root root   134 Nov  8 09:05 .gitmodules
-rw-r--r-- 1 root root  5922 Nov  8 09:05 FAQ.md
-rw-r--r-- 1 root root  7620 Nov  8 09:05 FOR_DEVS.md
-rw-r--r-- 1 root root 35149 Nov  8 09:05 LICENSE
-rw-r--r-- 1 root root  2623 Nov  8 09:05 README.md
-rwxr-xr-x 1 root root 22600 Nov  8 09:05 build-loader.sh
-rw-r--r-- 1 root root   123 Nov  8 09:05 bundled-exts.json
drwxr-xr-x 2 root root    40 Nov  8 06:26 cache
drwxr-xr-x 5 root root  4096 Nov  8 09:05 config
drwxr-xr-x 2 root root    40 Nov  8 06:26 custom
drwxr-xr-x 2 root root  4096 Nov  8 09:05 docs
drwxr-xr-x 5 root root  4096 Nov  8 09:05 ext
-rwxr-xr-x 1 root root 42782 Nov  8 09:05 ext-manager.sh
drwxr-xr-x 2 root root    40 Nov  8 06:26 images
drwxr-xr-x 3 root root  4096 Nov  8 09:05 include
drwxr-xr-x 2 root root  4096 Nov  8 09:05 tools
**drwxr-xr-x 2 root root    40 Nov  8 08:47 user_config.json**
root@redpill-tool-chain:/opt#
///////////////////////////////////////////////////////////////////////////////////////////////
我编写config.json 确实是正确的。
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master# ls -la
total 40
drwxrwxrwx 1 hankyang hankyang  4096 Nov  8 14:58 .
drwxrwxrwx 1 hankyang hankyang  4096 Nov  8 14:20 ..
-rwxrwxrwx 1 hankyang hankyang   291 Nov  7 15:50 .editorconfig
drwxrwxrwx 1 hankyang hankyang  4096 Nov  7 15:50 .github
-rwxrwxrwx 1 hankyang hankyang    37 Nov  7 15:50 .gitignore
-rwxrwxrwx 1 hankyang hankyang  5581 Nov  8 14:43 README.md
-rwxrwxrwx 1 hankyang hankyang  6754 Nov  7 15:50 README_EN.md
**-rwxrwxrwx 1 hankyang hankyang   210 Nov  8 16:55 apollolake_user_config.json
-rwxrwxrwx 1 hankyang hankyang   206 Nov  8 16:55 bromolow_user_config.json**
drwxrwxrwx 1 hankyang hankyang  4096 Nov  7 15:50 cache
drwxrwxrwx 1 hankyang hankyang  4096 Nov  8 14:41 custom
drwxrwxrwx 1 hankyang hankyang  4096 Nov  7 15:50 docker
-rwxrwxrwx 1 hankyang hankyang  7023 Nov  7 15:50 global_config.json
drwxrwxrwx 1 hankyang hankyang  4096 Nov  7 15:50 images
drwxrwxrwx 1 hankyang hankyang  4096 Nov  8 14:54 my
-rwxrwxrwx 1 hankyang hankyang 14729 Nov  7 15:50 redpill_tool_chain.sh
-rwxrwxrwx 1 hankyang hankyang   208 Nov  7 15:50 sample_user_config.json
-rwxrwxrwx 1 hankyang hankyang   540 Nov  7 15:50 synoboot.sh
root@WS-TV-002:~/nas/Downloads/redpill-tool-chain-master#
///////////////////////////////////////////////////////////////////////////////////////////////
我尝试在Docker下删除这个目录，然后新建一个user.config.json但是无法删除。
root@redpill-tool-chain:/opt# rm -rf /opt/redpill-load/user_config.json/
rm: cannot remove '/opt/redpill-load/user_config.json/': Device or resource busy
root@redpill-tool-chain:/opt#
//////////////////////////////////////////////////////////////////////////////////////////////
最后没办法了，向你求助

运行环境Ubuntu 20 + win10 pro
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master# docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.1
 Built:             Fri Oct  8 22:34:34 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@WS-TV-002:/nas/Downloads/redpill-tool-chain-master#

**Comment by windsorcerer** [comment]
补充说明，我尝试用 clean All 命令，重试了几次都是如此

**Comment by tossp** [comment]
复制`sample_user_config.json为`bromolow_user_config.json`

**Comment by windsorcerer** [comment]
我有复制sample_user_config.json为bromolow_user_config.json，问题是一样的，所以我当前打算更换一下环境。

**Comment by tossp** [comment]
`cat: /opt/redpill-load/user_config.json: Is a directory` 报错点
这里并没有加载到配置文件，docker自动创建了一个目录

**Comment by windsorcerer** [comment]
我也发现了这个问题，还尝试在Docker里面重新建立这个文件，但是Docker CLS下不允许删除。但目录下确实存在bromolow_user_config.json文件，不知道为什么这个文件没有被提取到，我查看Docker下的Mount列表，好像是直接Mount到目录下的文件。

**Comment by tossp** [comment]
我没法复现你的场景，没法判断你的问题出在哪里
`/opt/redpill-load/user_config.json`是根据你当前的平台去挂载的`bromolow_user_config.json`文件
`global_config.json`定义了你挂载文件的名称，我能提供的想法就这么多了

**Comment by windsorcerer** [comment]
非常感谢。等我解决这个问题我会回来留言的

**Comment by windsorcerer** [comment]
我买了国外的服务器，一次编译成功！！还是环境的锅啊！！！多谢支持

**Comment by tossp** [comment]
那个，，，，不用买服务器啊，，，，GitHub可以编译。。。。。。你看我上面的链接
