### ISSUE TITLE
编译失败，报错executor failed running

### ISSUE THREAD

**Issue by galaxy-eye** [tossp/redpill-tool-chain#235]
以前编译是正常，今天想编译个7.0.1版本的发现报错，测试了下7.1.0的也报错
executor failed running [/bin/sh -c apt-get update &&     apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod &&     rm -rf /var/lib/apt/lists/* /tmp/* &&     curl --progress-bar --output /usr/bin/jq --location https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/bin/jq]: exit code: 100
Error: Process completed with exit code 1.

顺便问下我是kvm虚拟机，网卡是redhat virtio类型的，用默认的virtio驱动网卡一直没法识别，只能改成e1000网卡用着，大佬知道kvm redhat virtio类型网卡加哪个驱动嘛

**Comment by tossp** [comment]
修复

**Comment by galaxy-eye** [comment]
已尝试重新编译成功
