### ISSUE TITLE
关于 7.1.1-42962 版本配置

### ISSUE THREAD

**Issue by lekoOwO** [tossp/redpill-tool-chain#240]
想请问 3615 的 7.1.1-42962 版本应该如何编译
是否能提点一下，谢谢

**Comment by tossp** [comment]
https://github.com/tossp/redpill-tool-chain/actions/runs/3597167839/jobs/6058643156

是正常编译的

**Comment by lekoOwO** [comment]
> 

好像没看到 42962 版本的

**Comment by lekoOwO** [comment]
改用 arpl 了，感谢！
