### ISSUE TITLE
The error "git clone" occurred

### ISSUE THREAD

**Issue by chdeast** [tossp/redpill-tool-chain#247]
Dear, the following mistakes always occur. What should I do?
“
> [stage-1  4/11] RUN git clone https://github.com/jimmyGALLAND/redpill-lkm.git  -b develop  /opt/redpill-lkm &&     git clone https://github.com/pocopico/redpill-load.git -b develop /opt/redpill-load:
#7 1.046 Cloning into '/opt/redpill-lkm'...
#7 1.878 fatal: Remote branch develop not found in upstream origin
------
executor failed running [/bin/sh -c git clone ${REDPILL_LKM_REPO}  -b ${REDPILL_LKM_BRANCH}  ${REDPILL_LKM_SRC} &&     git clone ${REDPILL_LOAD_REPO} -b ${REDPILL_LOAD_BRANCH} ${REDPILL_LOAD_SRC}]: exit code: 128
”

**Comment by tossp** [comment]
The upstream code warehouse is changed and needs to be adjusted
