### ISSUE TITLE
每次auto的时候都报错

### ISSUE THREAD

**Issue by lucasjingcn** [tossp/redpill-tool-chain#252]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]

环境：ubuntu 22.04 ，ubuntu18.04 都试过

求解。

**Comment by tossp** [comment]
参考这里处理 #149
