### ISSUE TITLE
求助！同时安装virtio和mpt3sas驱动，无法取得ip，只安装virtio驱动可以正常使用。

### ISSUE THREAD

**Issue by kaiyi88** [tossp/redpill-tool-chain#26]
同时安装virtio和mpt3sas驱动，无法取得ip，只安装virtio驱动可以正常使用。

**Comment by tossp** [comment]
`mpt3sas`驱动我就没成功过，我两块同规格型号的ssd，只能识别到一块

**Comment by tossp** [comment]
#pocopico/rp-ext/issues/23

跟多信息查看这里
