### ISSUE TITLE
Build Problem with 4 net 

### ISSUE THREAD

**Issue by devid79** [tossp/redpill-tool-chain#28]
Hello when add more net 

    "extra_cmdline": {
        "pid": "0x0951",
        "vid": "0x1625",
	"netif_num": "4",
        "sn": "1710LWN023200",
        "mac1": "001132410000"
	"mac2": "001132410000"
	"mac3": "001132410000"
	"mac4": "001132410000"
    },
    "synoinfo": {},
    "ramdisk_copy": {},
    "extensions": []

the result is 
[#] Checking runtime for required tools... [OK]
include/json.sh: line 16: 2: unbound variable
Makefile:29: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1

with one interface it's all ok

More thank in advantage

**Comment by tossp** [comment]
JSON syntax error and the MAC address cannot be the same

```json
"extra_cmdline": {
    "pid": "0x0951",
    "vid": "0x1625",
    "netif_num": "4",
    "sn": "1710LWN023200",
    "mac1": "001132410000",
    "mac2": "001132410001",
    "mac3": "001132410002",
    "mac4": "001132410003"
},
"synoinfo": {
    "maxlanport": "4"
},
"ramdisk_copy": {},
"extensions": []
```
