### ISSUE TITLE
依然编译失败

### ISSUE THREAD

**Issue by lukemin** [tossp/redpill-tool-chain#3]
'''root@instance-20210811-1316:/home/ubuntu/redpill-tool-chain# ./redpill_tool_chain.sh auto  bromolow-7.0.1-42218
Checking if redpill-lkm sources require pull.
  Nothing to do.
Check if redpill-load sources require pull.
  Nothing to do.
Lay back and enjoy the show: Magic is about to happen!
make[1]: Entering directory '/opt/redpill-lkm'
make -C /opt/toolkit_dev-bromolow-7.0.1-42218 M=/opt/redpill-lkm RP_MODULE_TARGET="dev" RP_MODULE_TARGET_VER="7" modules
make[2]: Entering directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
RP-TARGET SPECIFIED AS dev v7
  CC [M]  /opt/redpill-lkm/compat/string_compat.o
  CC [M]  /opt/redpill-lkm/internal/helper/math_helper.o
  CC [M]  /opt/redpill-lkm/internal/helper/memory_helper.o
  CC [M]  /opt/redpill-lkm/internal/helper/symbol_helper.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_toolbox.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_notifier_list.o
  CC [M]  /opt/redpill-lkm/internal/scsi/scsi_notifier.o
  CC [M]  /opt/redpill-lkm/internal/override/override_symbol.o
  CC [M]  /opt/redpill-lkm/internal/override/override_syscall.o
  CC [M]  /opt/redpill-lkm/internal/intercept_execve.o
  CC [M]  /opt/redpill-lkm/internal/call_protected.o
  CC [M]  /opt/redpill-lkm/internal/intercept_driver_register.o
  CC [M]  /opt/redpill-lkm/internal/stealth/sanitize_cmdline.o
  CC [M]  /opt/redpill-lkm/internal/stealth.o
  CC [M]  /opt/redpill-lkm/internal/virtual_pci.o
  CC [M]  /opt/redpill-lkm/internal/uart/uart_swapper.o
  CC [M]  /opt/redpill-lkm/internal/uart/vuart_virtual_irq.o
  CC [M]  /opt/redpill-lkm/internal/uart/virtual_uart.o
  CC [M]  /opt/redpill-lkm/internal/ioscheduler_fixer.o
  CC [M]  /opt/redpill-lkm/config/cmdline_delegate.o
  CC [M]  /opt/redpill-lkm/config/runtime_config.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/boot_shim_base.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/usb_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.o
In file included from /opt/redpill-lkm/shim/boot_dev/fake_sata_boot_shim.c:46:0:
/opt/redpill-lkm/compat/toolkit/include/../drivers/usb/storage/usb.h:50:2: warning: #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit" [-Wcpp]
 #warning "Using compatibility file for drivers/usb/storage/usb.h - if possible do NOT compile using toolkit"
  ^
  CC [M]  /opt/redpill-lkm/shim/boot_dev/native_sata_boot_shim.o
  CC [M]  /opt/redpill-lkm/shim/boot_device_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/smart_shim.o
  CC [M]  /opt/redpill-lkm/shim/storage/sata_port_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwcap_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_hwmon_shim.o
  CC [M]  /opt/redpill-lkm/shim/bios/rtc_proxy.o
  CC [M]  /opt/redpill-lkm/shim/bios/bios_shims_collection.o
  CC [M]  /opt/redpill-lkm/shim/bios_shim.o
  CC [M]  /opt/redpill-lkm/shim/block_fw_update_shim.o
  CC [M]  /opt/redpill-lkm/shim/disable_exectutables.o
  CC [M]  /opt/redpill-lkm/shim/pci_shim.o
  CC [M]  /opt/redpill-lkm/shim/pmu_shim.o
  CC [M]  /opt/redpill-lkm/shim/uart_fixer.o
  CC [M]  /opt/redpill-lkm/redpill_main.o
  LD [M]  /opt/redpill-lkm/redpill.o
  Building modules, stage 2.
RP-TARGET SPECIFIED AS dev v7
  MODPOST 1 modules
  CC      /opt/redpill-lkm/redpill.mod.o
  LD [M]  /opt/redpill-lkm/redpill.ko
make[2]: Leaving directory '/opt/toolkit_dev-bromolow-7.0.1-42218'
make[1]: Leaving directory '/opt/redpill-lkm'
#############################################
filename:       /opt/redpill-lkm/redpill.ko
license:        GPL
version:        v0.5-at-2021_10_14-05_45_55
author:         TTG
retpoline:      Y
srcversion:     9D5817BD80754EFE921A0AC
depends:        
vermagic:       3.10.108 SMP mod_unload 
#############################################
Using user_config.json:
{
    "extra_cmdline": {
        "pid": "0x1234",
        "vid": "0xabcd",
        "sn": "1591xxxxxxxxx",
        "mac1": "0xxxxxxxxxxx"
    },
    "synoinfo": {},
    "ramdisk_copy": {},
    "extensions": []
}#############################################
/opt/redpill-load /opt
[#] Checking runtime for required tools... [OK]
include/json.sh: line 16: 2: unbound variable
Makefile:29: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1

**Comment by tossp** [comment]
昨天补了 github actions 在里面做了全平台验证，都是成功了的

嗯，看着像jq的语法bug，json没有注释，可以删除

json文件末尾最后试着给一个空行

**Comment by hncsjmj** [comment]
root@ubuntu-867007:~/dsm# ./redpill_tool_chain.sh build ds918p_user_config.json
Error: Platform version ds918p_user_config.json not specified in global_config.json

Usage: ./redpill_tool_chain.sh <action> <platform version>

Actions: build, auto, run, clean, add, del, sn, pat

- build:    Build the toolchain image for the specified platform version.

- auto:     Starts the toolchain container using the previosuly build toolchain image for the specified platform.
            Updates redpill sources and builds the bootloader image automaticaly. Will end the container once done.

- run:      Starts the toolchain container using the previously built toolchain image for the specified platform.
            Interactive Bash terminal.

- clean:    Removes old (=dangling) images and the build cache for a platform version.
            Use ‘all’ as platform version to remove images and build caches for all platform versions.

- add:      To install extension you need to know its index file location and nothing more.
            eg: add 'https://example.com/some-extension/rpext-index.json'

- del:      To remove an already installed extension you need to know its ID.
            eg: del 'example_dev.some_extension'

- sn:       Generates a serial number and mac address for the following platforms
            DS3615xs DS3617xs DS916+ DS918+ DS920+ DS3622xs+ FS6400 DVA3219 DVA3221 DS1621+
            eg: sn ds920p

- pat:      For decoding PAT file. see: https://github.com/tossp/redpill-tool-chain/blob/master/.github/workflows/pat.yml

Available platform versions:
---------------------
ds1621p-7.0.1-42218
ds1621p-7.1.0-42661
ds2422p-7.0.1-42218
ds3615xs-6.2.4-25556
ds3615xs-7.0.1-42218
ds3615xs-7.1.0-42661
ds3617xs-7.0.1-42218
ds3617xs-7.1.0-42661
ds3622xsp-7.0.1-42218
ds3622xsp-7.1.0-42661
ds918p-6.2.4-25556
ds918p-7.0.1-42218
ds918p-7.1.0-42661
ds920p-7.0.1-42218
ds920p-7.1.0-42661
dva3221-7.0.1-42218
dva3221-7.1.0-42661

Custom Extensions:
---------------------
pocopico.aic94xx
pocopico.arcmsr
pocopico.e1000
pocopico.e1000e
pocopico.igb
pocopico.ixgbe
pocopico.mpt3sas
pocopico.mvsas
pocopico.r8125
pocopico.r8152
pocopico.r8168
pocopico.r8169
pocopico.redpill
pocopico.redpilldev
pocopico.sata_nv
pocopico.sky2
pocopico.vmxnet3
redpill-acpid
redpill-boot-wait
redpill-dtb-static

Check global_settings.json for settings.
root@ubuntu-867007:~/dsm#

我的报这个错，头疼死了， arm 版的 ubuntu 编译，无法安装 libsdl2-mixer
