### ISSUE TITLE
include/json.sh: line 16: 2: unbound variable

### ISSUE THREAD

**Issue by sunnygor** [tossp/redpill-tool-chain#31]
[#] Checking runtime for required tools... [OK]
include/json.sh: line 16: 2: unbound variable
make: *** [Makefile:33: build_redpill_load] Error 1
sunny@sunleilei:~$

编译到最后就出现这个错误，baidu、google找不到同样的情况，Linux基础不足，排不了错，帮忙解释一下

**Comment by tossp** [comment]
隐藏敏感信息后贴出你的配置

**Comment by tossp** [comment]
看报错，应该是你的配置文件语法错误

**Comment by tossp** [comment]
@sunnygor ping
