### ISSUE TITLE
not fount virtual net adapter 

### ISSUE THREAD

**Issue by sor88** [tossp/redpill-tool-chain#42]
Not fount virtual net adapter after update to 7.0.1-42218.
boot image: redpill-DS918+_7.0.1-42218_b1643132265.img

**Comment by sor88** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/15c6f3ad-1e5e-493f-9255-cad8f6791a95-5545739e-1fa6-454f-ade4-bb0fc154819c-v1.png?transparent=1&palette=1&width=246)
When do you give me an answer?

**Comment by tossp** [comment]
Have you added the corresponding network card driver？

cc: https://github.com/pocopico/rp-ext
