### ISSUE TITLE
制作镜像过程中下载驱动的时候可以改一下地址吗

### ISSUE THREAD

**Issue by LxnChan** [tossp/redpill-tool-chain#43]
![image](https://user-images.githubusercontent.com/46388610/151331637-5cad725b-e961-4bf0-82c3-287df45dbd7b.png)

这个地址有办法改一下吗，我这在云服务器上编译，裸连github实在有点困难，我自己有cf的Github代理，如果有代理的话就会好很多。

**Comment by tossp** [comment]
你需要改插件配置，改挺多的，用户代理的话参考linux全局代理配置，就是给镜像一个https_proxy的环境变量

PS：用[github actions](https://github.com/tossp/redpill-tool-chain/) 在线编译不好吗？
担心sn/mac泄露的话，查看我的[其他编译分支](https://github.com/tossp/redpill-tool-chain/runs/4748814984?check_suite_focus=true)，怎么引入加密变量，自己在做一个oss加密回传就可以了
我偷懒，没做oss加密回传，编译就几分钟，自己下了就删
