### ISSUE TITLE
bromolow-7.0.1-42218 编译成功 但无法引导

### ISSUE THREAD

**Issue by wulangbnu** [tossp/redpill-tool-chain#45]
bromolow-7.0.1-42218 添加了扩展驱动

* jumkey.acpid2 (https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-acpid/rpext-index.json)        
* thethorgroup.boot-wait (https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-boot-wait/rpext-index.json)
* thethorgroup.virtio (https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-virtio/rpext-index.json)

成功编译 redpill-DS3615xs_7.0.1-42218_xxx.img 文件，但引导后直接出如下的 grub> 界面

![image](https://user-images.githubusercontent.com/5148787/151701679-76a3d2e2-60fe-4cc5-ae02-7f6a5fd3a5e1.png)

不知道哪一步出问题了，谢谢指教

**Comment by sor88** [comment]
you can boot from the first disk or image file attach it as a disk

**Comment by wulangbnu** [comment]
> you can boot from the first disk or image file attach it as a disk

I boot from image file as attach it as a disk, but failed. It shows the "grub> " screen.

**Comment by tossp** [comment]
这个需要看串口日志了
