### ISSUE TITLE
ds918p_42218.pat 校验错误

### ISSUE THREAD

**Issue by linszx** [tossp/redpill-tool-chain#46]
`[!] Checksum mismatch - expected 4fc59b0f0adfdd96467376f50919dde1bf5dcec74e53452e626f9cf7bd52a38c but computed a403809ab2cd476c944fdfa18cae2c2833e4af36230fa63f0cdee31a92bebba2

*** Process will exit ***
`

1-13发布了一个小更新，请问是否已经支持
Version: 7.0.1-42218 Update 2
(2022-01-13)

**Comment by tossp** [comment]
感谢回馈，这个很早就修复了

**Comment by tossp** [comment]
还没支持，需要重制补丁

**Comment by goguo** [comment]
负责校验的是那个模块,能否修改这两个检验码 使其匹配呢?
