### ISSUE TITLE
进行到最后一步报错，无法生成镜像

### ISSUE THREAD

**Issue by fengliuaitianxia** [tossp/redpill-tool-chain#50]
执行这条命令“./redpill_tool_chain.sh auto apollolake-7.0.1-42218”后报错，请问大佬这个这么解决。用的Qv2ray翻墙，用curl
命令看google是有返回的。
![image](https://user-images.githubusercontent.com/54541426/153715749-40bdce48-4964-4dbd-817f-c6efb2d95b32.png)

**Comment by tossp** [comment]
证书验证错误，有可能是你的翻墙点没返回正确的证书，你是不是拉取的比较老的版本，新版的忽略了证书验证

**Comment by fengliuaitianxia** [comment]
我拉取的就是https://github.com/tossp/redpill-tool-chain这个版本，是最新的。我换了个机场，用clash还是不行，用curl命令是可以在终端打开那些网站，但是还是报错下载不了。可能换的这个机场也还是不行

**Comment by tossp** [comment]
没有特别机密的资料，自行使用github actions编译吧
