### ISSUE TITLE
USB disk support

### ISSUE THREAD

**Issue by emiliannicu** [tossp/redpill-tool-chain#56]
Is usbportcfg supported in sample_user_config.json?

https://xpenology.com/forum/topic/32986-external-hdds-detected-as-internal-hdd-after-synoinfoconf-edit/

**Comment by tossp** [comment]
`sample_user_config.json` is a file that can customize the configuration

You can refer to [here](https://github.com/tossp/redpill-tool-chain/blob/master/.github/workflows/test.yml#L68) to make some custom modifications
