### ISSUE TITLE
2022.2.28编译最新引导 似乎无法实现定时开关机

### ISSUE THREAD

**Issue by zhuzizhao1** [tossp/redpill-tool-chain#59]
技术高超的tossp大佬，我在2月28日使用您的最新redpill-tool-chain编译了dsm 918+ 7.0.1 42218的引导，经过安装后成功由dsm6.2.3升级到dsm7.0.1，但是定时开关机功能失效了，晚上可以正常定时关机，但是早上定时开机似乎失效了，这在之前是正常的，我使用的机器是自己组装的，cpu是g4400t，主板 微星110m pro d，接了2块sata硬盘，除了定时开关机一切正常，请告诉我我这是缺少驱动导致的吗？有什么办法可以解决这一问题，请赐教，感谢。

**Comment by tossp** [comment]
抱歉，这个完全涉及到我技巧知识的盲区，你可以尝试去xpenology的ddr区和其他人讨论更多细节

**Comment by psonys** [comment]
试试看添加一个acpi的驱动

**Comment by mmgzyjh** [comment]
定时开机可以在BIOS设置呀

**Comment by zhuzizhao1** [comment]
> 定时开机可以在BIOS设置呀

举个例子，我在主板bios设置早上七点开机，只要我群晖开机，同步东八区时间，假设到了早上七点，而主板的时间就会是晚上十一点，根本无法实现开机；相反我如果设置群晖为伦敦的0时区，群晖的时间不对了，主板的时间则是正常的，我不知道会有多大影响但想来会出问题。

**Comment by zhuzizhao1** [comment]
> 试试看添加一个acpi的驱动

请问是这个驱动吗[redpill-acpid](https://github.com/pocopico/rp-ext/tree/main/redpill-acpid)，我看到下面解释说ACPI Daemon v2 that handles power button events，这是只针对关机按键的驱动

**Comment by zhuzizhao1** [comment]
> 抱歉，这个完全涉及到我技巧知识的盲区，你可以尝试去xpenology的ddr区和其他人讨论更多细节

感谢您的回复，我去那里看了暂时未得到有用信息，我将在vm虚拟机上进一步测试下，希望能得到更多的细节，现在基本确定，就是只要群晖正常开机，就会将主板时间调慢8小时。所以导致定时开机出现问题。
