### ISSUE TITLE
Is there any way to run the tool chain with gitbash in Windows 10?

### ISSUE THREAD

**Issue by PeterSuh-Q3** [tossp/redpill-tool-chain#61]
The installation of git bash, docker for win (with wsl kernel update), and jq for win was completed within window 10, and the shell was performed at the git bash prompt as follows. But Bottom line : [#9 ERROR: failed to walk) An error occurred whether the message was the cause.
The log is as follows. Can you solve this problem, Tossp?

------------------------------------------------------------------------------------------------------------------------------------------

dante@DESKTOP-HHRJFHR MINGW64 /e/redpill-tool-chain-master
$ ./redpill_tool_chain.sh
./redpill_tool_chain.sh: line 8: [: /c/Program: unary operator expected
Usage: ./redpill_tool_chain.sh <action> <platform version>

Actions: build, auto, run, clean

- build:    Build the toolchain image for the specified platform version.

- auto:     Starts the toolchain container using the previosuly build toolchain image for the specified platform.
            Updates redpill sources and builds the bootloader image automaticaly. Will end the container once done.

- run:      Starts the toolchain container using the previously built toolchain image for the specified platform.
            Interactive Bash terminal.

- clean:    Removes old (=dangling) images and the build cache for a platform version.
            Use ‘all’ as platform version to remove images and build caches for all platform versions.

- add:      To install extension you need to know its index file location and nothing more.
            eg: add 'https://example.com/some-extension/rpext-index.json'

- del:      To remove an already installed extension you need to know its ID.
            eg: del 'example_dev.some_extension'

Available platform versions:
---------------------
bromolow-6.2.4-25556
bromolow-7.0-41222
bromolow-7.0.1-42218
apollolake-6.2.4-25556
apollolake-7.0-41890
apollolake-7.0.1-42218
broadwell-7.0.1-42218
broadwellnk-7.0.1-42218
geminilake-7.0.1-42218

Custom Extensions:
---------------------
[Nothing]

Check global_settings.json for settings.

dante@DESKTOP-HHRJFHR MINGW64 /e/redpill-tool-chain-master
$ ./redpill_tool_chain.sh build broadwellnk-7.0.1-42218
./redpill_tool_chain.sh: line 8: [: /c/Program: unary operator expected

#1 [internal] load build definition from Dockerfile
#1 sha256:5a65977fb4e76ae65f4cc18e552a99aa36f567708e02fc4010f2b66fe1fa582b
#1 transferring dockerfile: 2.60kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:e847f1f0f8f229b393ad9d1c0f68a1d7a21458da519704845438222e0179ff66
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/debian:10-slim
#3 sha256:bb2045be78b720556afe835d68d0b202bbfa66fa3140b0ec6eaa445d664ba201
#3 DONE 2.9s

#4 [extract 1/2] FROM docker.io/library/debian:10-slim@sha256:e61cffb42ef0dbb31832d4543d6998ab9125210d0136bc0aed65cc753cee9125
#4 sha256:e990d8a5dee15f329d52d895a91f589257fb84cc8181bbf4dbd6e598bf73c59e
#4 resolve docker.io/library/debian:10-slim@sha256:e61cffb42ef0dbb31832d4543d6998ab9125210d0136bc0aed65cc753cee9125 done
#4 sha256:09904dab2f4100eee259d1f77a49f2101a8b694959c401c799622b6fe1c203b5 1.46kB / 1.46kB done
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 0B / 27.15MB 0.1s
#4 sha256:e61cffb42ef0dbb31832d4543d6998ab9125210d0136bc0aed65cc753cee9125 1.85kB / 1.85kB done
#4 sha256:e847f59f3eeb921647a66e95ebf849f442eb7ebabbdb3dd3d1ea07689871b1a5 529B / 529B done
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 3.15MB / 27.15MB 0.4s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 5.72MB / 27.15MB 0.5s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 10.49MB / 27.15MB 0.7s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 12.58MB / 27.15MB 0.8s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 15.73MB / 27.15MB 0.9s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 17.83MB / 27.15MB 1.0s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 19.92MB / 27.15MB 1.1s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 23.07MB / 27.15MB 1.2s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 27.15MB / 27.15MB 1.4s
#4 sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 27.15MB / 27.15MB 1.5s done
#4 extracting sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 0.1s
#4 extracting sha256:15115158dd02a1bf2fd28724e3c1024394033fb0e9a5d3e451ed2715b6ae312d 1.3s done
#4 DONE 2.9s

#5 [stage-1 2/9] RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak &&    sed  -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/security.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/security.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list &&    apt-get update &&    apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod &&    rm -rf /var/lib/apt/lists/* /tmp/* &&    curl --progress-bar --output /usr/bin/jq --location https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/bin/jq
#5 sha256:0258fab799c33e116d8458632b2c8caa563e4e109b6170174460e2da74e4d348
#5 ...

#7 [internal] load build context
#7 sha256:607cd11c8309236d25136a160211e8ccbf5aa9007bd952b3e9521b2dc80db507
#7 transferring context: 359.58MB 3.0s done
#7 DONE 3.0s

#8 [extract 2/2] ADD downloads/ds.broadwellnk-7.0.dev.txz /
#8 sha256:390189bacf53ab8f241fd010b84fedfb008f7ee8138d3298b393a5d6076bfa27
#8 ...

#5 [stage-1 2/9] RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak &&    sed  -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/security.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/security.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list &&    apt-get update &&    apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod &&    rm -rf /var/lib/apt/lists/* /tmp/* &&    curl --progress-bar --output /usr/bin/jq --location https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/bin/jq
#5 sha256:0258fab799c33e116d8458632b2c8caa563e4e109b6170174460e2da74e4d348
#5 0.497 Get:1 http://mirrors.aliyun.com/debian buster InRelease [122 kB]
#5 0.513 Get:2 http://mirrors.aliyun.com/debian-security buster/updates InRelease [65.4 kB]
#5 0.521 Get:3 http://mirrors.aliyun.com/debian buster-updates InRelease [51.9 kB]
#5 0.583 Get:4 http://mirrors.aliyun.com/debian buster/main amd64 Packages [7906 kB]
#5 0.930 Get:5 http://mirrors.aliyun.com/debian-security buster/updates/main amd64 Packages [317 kB]
#5 0.937 Get:6 http://mirrors.aliyun.com/debian buster-updates/main amd64 Packages [8792 B]
#5 1.780 Fetched 8470 kB in 1s (5813 kB/s)
#5 1.780 Reading package lists...
#5 2.242 Reading package lists...
#5 2.683 Building dependency tree...
#5 2.770 Reading state information...
#5 2.846 The following additional packages will be installed:
#5 2.847  binutils binutils-common binutils-x86-64-linux-gnu bzip2 cpp cpp-8 dpkg-dev
#5 2.849  g++ g++-8 gcc gcc-8 gettext-base git-man libasan5 libatomic1 libbinutils
#5 2.849  libbison-dev libc-dev-bin libc6-dev libcc1-0 libcroco3 libcurl3-gnutls
#5 2.849  libcurl4 libdpkg-perl liberror-perl libexpat1 libgcc-8-dev libgdbm-compat4
#5 2.849  libgdbm6 libglib2.0-0 libgomp1 libgpm2 libgssapi-krb5-2 libicu63 libisl19
#5 2.849  libitm1 libk5crypto3 libkeyutils1 libkmod2 libkrb5-3 libkrb5support0
#5 2.849  libldap-2.4-2 libldap-common liblsan0 libmpc3 libmpfr6 libmpx2 libncurses6
#5 2.849  libnghttp2-14 libpcre2-8-0 libperl5.28 libpsl5 libquadmath0 libreadline7
#5 2.849  librtmp1 libsasl2-2 libsasl2-modules-db libsigsegv2 libssh2-1 libssl1.1
#5 2.849  libstdc++-8-dev libtsan0 libubsan1 libxml2 linux-libc-dev lsb-base m4 make
#5 2.849  openssl patch perl perl-modules-5.28 readline-common vim-common vim-runtime
#5 2.849  xxd xz-utils
#5 2.849 Suggested packages:
#5 2.849  binutils-doc bison-doc bzip2-doc libarchive1 cpp-doc gcc-8-locales
#5 2.849  debian-keyring flex-doc g++-multilib g++-8-multilib gcc-8-doc
#5 2.849  libstdc++6-8-dbg gcc-multilib manpages-dev autoconf automake libtool gdb
#5 2.849  gcc-doc gcc-8-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
#5 2.849  libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg
#5 2.849  libquadmath0-dbg gettext-doc autopoint libasprintf-dev libgettextpo-dev
#5 2.849  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
#5 2.849  gitweb git-cvs git-mediawiki git-svn glibc-doc gnupg | gnupg2 sensible-utils
#5 2.849  bzr gdbm-l10n gpm krb5-doc krb5-user libssl-doc libstdc++-8-doc m4-doc
#5 2.849  make-doc ed diffutils-doc perl-doc libterm-readline-gnu-perl
#5 2.849  | libterm-readline-perl-perl libb-debug-perl liblocale-codes-perl
#5 2.849  readline-doc ctags vim-doc vim-scripts
#5 2.849 Recommended packages:
#5 2.849  fakeroot gnupg | gnupg2 libalgorithm-merge-perl libfl-dev less ssh-client
#5 2.849  manpages manpages-dev libfile-fcntllock-perl liblocale-gettext-perl
#5 2.849  libglib2.0-data shared-mime-info xdg-user-dirs krb5-locales publicsuffix
#5 2.849  libsasl2-modules netbase
#5 3.211 The following NEW packages will be installed:
#5 3.211  bc binutils binutils-common binutils-x86-64-linux-gnu bison bsdiff
#5 3.211  build-essential bzip2 ca-certificates cpio cpp cpp-8 curl dosfstools
#5 3.217  dpkg-dev flex g++ g++-8 gcc gcc-8 gettext gettext-base git git-man kmod
#5 3.217  libasan5 libatomic1 libbinutils libbison-dev libc-dev-bin libc6-dev libcc1-0
#5 3.217  libcroco3 libcurl3-gnutls libcurl4 libdpkg-perl liberror-perl libexpat1
#5 3.217  libgcc-8-dev libgdbm-compat4 libgdbm6 libglib2.0-0 libgomp1 libgpm2
#5 3.217  libgssapi-krb5-2 libicu63 libisl19 libitm1 libk5crypto3 libkeyutils1
#5 3.217  libkmod2 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblsan0
#5 3.217  libmpc3 libmpfr6 libmpx2 libncurses6 libnghttp2-14 libpcre2-8-0 libperl5.28
#5 3.217  libpsl5 libquadmath0 libreadline7 librtmp1 libsasl2-2 libsasl2-modules-db
#5 3.217  libsigsegv2 libssh2-1 libssl-dev libssl1.1 libstdc++-8-dev libtsan0
#5 3.217  libubsan1 libxml2 linux-libc-dev lsb-base m4 make openssl patch perl
#5 3.217  perl-modules-5.28 readline-common vim vim-common vim-runtime xxd xz-utils
#5 3.234 0 upgraded, 91 newly installed, 0 to remove and 0 not upgraded.
#5 3.234 Need to get 91.1 MB of archives.
#5 3.234 After this operation, 375 MB of additional disk space will be used.
#5 3.234 Get:1 http://mirrors.aliyun.com/debian buster/main amd64 perl-modules-5.28 all 5.28.1-6+deb10u1 [2873 kB]
#5 3.365 Get:2 http://mirrors.aliyun.com/debian buster/main amd64 libgdbm6 amd64 1.18.1-4 [64.7 kB]
#5 3.367 Get:3 http://mirrors.aliyun.com/debian buster/main amd64 libgdbm-compat4 amd64 1.18.1-4 [44.1 kB]
#5 3.369 Get:4 http://mirrors.aliyun.com/debian buster/main amd64 libperl5.28 amd64 5.28.1-6+deb10u1 [3894 kB]
#5 3.538 Get:5 http://mirrors.aliyun.com/debian buster/main amd64 perl amd64 5.28.1-6+deb10u1 [204 kB]
#5 3.542 Get:6 http://mirrors.aliyun.com/debian buster/main amd64 libsigsegv2 amd64 2.12-2 [32.8 kB]
#5 3.542 Get:7 http://mirrors.aliyun.com/debian buster/main amd64 m4 amd64 1.4.18-2 [203 kB]
#5 3.547 Get:8 http://mirrors.aliyun.com/debian buster/main amd64 flex amd64 2.6.4-6.2 [456 kB]
#5 3.573 Get:9 http://mirrors.aliyun.com/debian buster/main amd64 cpio amd64 2.12+dfsg-9 [223 kB]
#5 3.576 Get:10 http://mirrors.aliyun.com/debian buster/main amd64 libssl1.1 amd64 1.1.1d-0+deb10u7 [1539 kB]
#5 3.648 Get:11 http://mirrors.aliyun.com/debian buster/main amd64 libkmod2 amd64 26-1 [52.7 kB]
#5 4.586 Get:12 http://mirrors.aliyun.com/debian buster/main amd64 lsb-base all 10.2019051400 [28.4 kB]
#5 4.588 Get:13 http://mirrors.aliyun.com/debian buster/main amd64 kmod amd64 26-1 [90.2 kB]
#5 5.134 Get:14 http://mirrors.aliyun.com/debian buster/main amd64 readline-common all 7.0-5 [70.6 kB]
#5 5.138 Get:15 http://mirrors.aliyun.com/debian buster/main amd64 xxd amd64 2:8.1.0875-5 [140 kB]
#5 8.808 Get:16 http://mirrors.aliyun.com/debian buster/main amd64 vim-common all 2:8.1.0875-5 [195 kB]
#5 8.815 Get:17 http://mirrors.aliyun.com/debian buster/main amd64 bzip2 amd64 1.0.6-9.2~deb10u1 [48.4 kB]
#5 8.817 Get:18 http://mirrors.aliyun.com/debian buster/main amd64 gettext-base amd64 0.19.8.1-9 [123 kB]
#5 8.831 Get:19 http://mirrors.aliyun.com/debian-security buster/updates/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-1+deb10u2 [69.2 kB]
#5 8.836 Get:20 http://mirrors.aliyun.com/debian-security buster/updates/main amd64 libsasl2-2 amd64 2.1.27+dfsg-1+deb10u2 [106 kB]
#5 8.840 Get:21 http://mirrors.aliyun.com/debian buster/main amd64 xz-utils amd64 5.2.4-1 [183 kB]
#5 8.845 Get:22 http://mirrors.aliyun.com/debian buster/main amd64 libncurses6 amd64 6.1+20181013-2+deb10u2 [102 kB]
#5 8.846 Get:23 http://mirrors.aliyun.com/debian buster/main amd64 libreadline7 amd64 7.0-5 [151 kB]
#5 8.850 Get:24 http://mirrors.aliyun.com/debian buster/main amd64 bc amd64 1.07.1-2+b1 [109 kB]
#5 8.853 Get:25 http://mirrors.aliyun.com/debian buster/main amd64 binutils-common amd64 2.31.1-16 [2073 kB]
#5 8.937 Get:26 http://mirrors.aliyun.com/debian buster/main amd64 libbinutils amd64 2.31.1-16 [478 kB]
#5 8.961 Get:27 http://mirrors.aliyun.com/debian buster/main amd64 binutils-x86-64-linux-gnu amd64 2.31.1-16 [1823 kB]
#5 9.034 Get:28 http://mirrors.aliyun.com/debian buster/main amd64 binutils amd64 2.31.1-16 [56.8 kB]
#5 9.035 Get:29 http://mirrors.aliyun.com/debian buster/main amd64 libbison-dev amd64 2:3.3.2.dfsg-1 [500 kB]
#5 9.062 Get:30 http://mirrors.aliyun.com/debian buster/main amd64 bison amd64 2:3.3.2.dfsg-1 [871 kB]
#5 9.093 Get:31 http://mirrors.aliyun.com/debian buster/main amd64 bsdiff amd64 4.3-21 [15.8 kB]
#5 9.094 Get:32 http://mirrors.aliyun.com/debian buster/main amd64 libc-dev-bin amd64 2.28-10 [275 kB]
#5 9.104 Get:33 http://mirrors.aliyun.com/debian buster/main amd64 linux-libc-dev amd64 4.19.208-1 [1482 kB]
#5 9.163 Get:34 http://mirrors.aliyun.com/debian buster/main amd64 libc6-dev amd64 2.28-10 [2691 kB]
#5 9.287 Get:35 http://mirrors.aliyun.com/debian buster/main amd64 libisl19 amd64 0.20-2 [587 kB]
#5 9.310 Get:36 http://mirrors.aliyun.com/debian buster/main amd64 libmpfr6 amd64 4.0.2-1 [775 kB]
#5 9.341 Get:37 http://mirrors.aliyun.com/debian buster/main amd64 libmpc3 amd64 1.1.0-1 [41.3 kB]
#5 9.344 Get:38 http://mirrors.aliyun.com/debian buster/main amd64 cpp-8 amd64 8.3.0-6 [8914 kB]
#5 9.722 Get:39 http://mirrors.aliyun.com/debian buster/main amd64 cpp amd64 4:8.3.0-1 [19.4 kB]
#5 9.722 Get:40 http://mirrors.aliyun.com/debian buster/main amd64 libcc1-0 amd64 8.3.0-6 [46.6 kB]
#5 9.722 Get:41 http://mirrors.aliyun.com/debian buster/main amd64 libgomp1 amd64 8.3.0-6 [75.8 kB]
#5 9.725 Get:42 http://mirrors.aliyun.com/debian buster/main amd64 libitm1 amd64 8.3.0-6 [27.7 kB]
#5 9.726 Get:43 http://mirrors.aliyun.com/debian buster/main amd64 libatomic1 amd64 8.3.0-6 [9032 B]
#5 9.726 Get:44 http://mirrors.aliyun.com/debian buster/main amd64 libasan5 amd64 8.3.0-6 [362 kB]
#5 9.741 Get:45 http://mirrors.aliyun.com/debian buster/main amd64 liblsan0 amd64 8.3.0-6 [131 kB]
#5 9.747 Get:46 http://mirrors.aliyun.com/debian buster/main amd64 libtsan0 amd64 8.3.0-6 [283 kB]
#5 9.758 Get:47 http://mirrors.aliyun.com/debian buster/main amd64 libubsan1 amd64 8.3.0-6 [120 kB]
#5 9.767 Get:48 http://mirrors.aliyun.com/debian buster/main amd64 libmpx2 amd64 8.3.0-6 [11.4 kB]
#5 9.767 Get:49 http://mirrors.aliyun.com/debian buster/main amd64 libquadmath0 amd64 8.3.0-6 [133 kB]
#5 9.769 Get:50 http://mirrors.aliyun.com/debian buster/main amd64 libgcc-8-dev amd64 8.3.0-6 [2298 kB]
#5 9.867 Get:51 http://mirrors.aliyun.com/debian buster/main amd64 gcc-8 amd64 8.3.0-6 [9452 kB]
#5 10.25 Get:52 http://mirrors.aliyun.com/debian buster/main amd64 gcc amd64 4:8.3.0-1 [5196 B]
#5 10.25 Get:53 http://mirrors.aliyun.com/debian buster/main amd64 libstdc++-8-dev amd64 8.3.0-6 [1532 kB]
#5 10.31 Get:54 http://mirrors.aliyun.com/debian buster/main amd64 g++-8 amd64 8.3.0-6 [9752 kB]
#5 10.71 Get:55 http://mirrors.aliyun.com/debian buster/main amd64 g++ amd64 4:8.3.0-1 [1644 B]
#5 10.71 Get:56 http://mirrors.aliyun.com/debian buster/main amd64 make amd64 4.2.1-1.2 [341 kB]
#5 10.72 Get:57 http://mirrors.aliyun.com/debian buster/main amd64 libdpkg-perl all 1.19.7 [1414 kB]
#5 10.78 Get:58 http://mirrors.aliyun.com/debian buster/main amd64 patch amd64 2.7.6-3+deb10u1 [126 kB]
#5 10.79 Get:59 http://mirrors.aliyun.com/debian buster/main amd64 dpkg-dev all 1.19.7 [1773 kB]
#5 12.35 Get:60 http://mirrors.aliyun.com/debian buster/main amd64 build-essential amd64 12.6 [7576 B]
#5 12.92 Get:61 http://mirrors.aliyun.com/debian buster/main amd64 openssl amd64 1.1.1d-0+deb10u7 [845 kB]
#5 13.24 Get:62 http://mirrors.aliyun.com/debian buster/main amd64 ca-certificates all 20200601~deb10u2 [166 kB]
#5 13.58 Get:63 http://mirrors.aliyun.com/debian buster/main amd64 libkeyutils1 amd64 1.6-6 [15.0 kB]
#5 14.14 Get:64 http://mirrors.aliyun.com/debian buster/main amd64 libkrb5support0 amd64 1.17-3+deb10u3 [65.8 kB]
#5 14.47 Get:65 http://mirrors.aliyun.com/debian buster/main amd64 libk5crypto3 amd64 1.17-3+deb10u3 [122 kB]
#5 21.78 Get:66 http://mirrors.aliyun.com/debian buster/main amd64 libkrb5-3 amd64 1.17-3+deb10u3 [370 kB]
#5 22.09 Get:67 http://mirrors.aliyun.com/debian buster/main amd64 libgssapi-krb5-2 amd64 1.17-3+deb10u3 [158 kB]
#5 22.40 Get:68 http://mirrors.aliyun.com/debian buster/main amd64 libldap-common all 2.4.47+dfsg-3+deb10u6 [90.0 kB]
#5 22.70 Get:69 http://mirrors.aliyun.com/debian buster/main amd64 libldap-2.4-2 amd64 2.4.47+dfsg-3+deb10u6 [224 kB]
#5 23.01 Get:70 http://mirrors.aliyun.com/debian buster/main amd64 libnghttp2-14 amd64 1.36.0-2+deb10u1 [85.0 kB]
#5 23.10 Get:71 http://mirrors.aliyun.com/debian buster/main amd64 libpsl5 amd64 0.20.2-2 [53.7 kB]
#5 23.42 Get:72 http://mirrors.aliyun.com/debian buster/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2 [60.5 kB]
#5 23.73 Get:73 http://mirrors.aliyun.com/debian buster/main amd64 libssh2-1 amd64 1.8.0-2.1 [140 kB]
#5 24.04 Get:74 http://mirrors.aliyun.com/debian buster/main amd64 libcurl4 amd64 7.64.0-4+deb10u2 [332 kB]
#5 24.59 Get:75 http://mirrors.aliyun.com/debian buster/main amd64 curl amd64 7.64.0-4+deb10u2 [265 kB]
#5 25.13 Get:76 http://mirrors.aliyun.com/debian buster/main amd64 dosfstools amd64 4.1-2 [98.4 kB]
#5 25.82 Get:77 http://mirrors.aliyun.com/debian buster/main amd64 libglib2.0-0 amd64 2.58.3-2+deb10u3 [1259 kB]
#5 26.05 Get:78 http://mirrors.aliyun.com/debian-security buster/updates/main amd64 libicu63 amd64 63.1-6+deb10u2 [8300 kB]
#5 26.78 Get:79 http://mirrors.aliyun.com/debian buster/main amd64 libxml2 amd64 2.9.4+dfsg1-7+deb10u2 [689 kB]
#5 27.12 Get:80 http://mirrors.aliyun.com/debian buster/main amd64 libcroco3 amd64 0.6.12-3 [145 kB]
#5 28.61 Get:81 http://mirrors.aliyun.com/debian buster/main amd64 gettext amd64 0.19.8.1-9 [1303 kB]
#5 ...

#8 [extract 2/2] ADD downloads/ds.broadwellnk-7.0.dev.txz /
#8 sha256:390189bacf53ab8f241fd010b84fedfb008f7ee8138d3298b393a5d6076bfa27
#8 DONE 29.2s

#5 [stage-1 2/9] RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak &&    sed  -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/security.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list &&    sed  -i "s/security.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list &&    apt-get update &&    apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod &&    rm -rf /var/lib/apt/lists/* /tmp/* &&    curl --progress-bar --output /usr/bin/jq --location https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/bin/jq
#5 sha256:0258fab799c33e116d8458632b2c8caa563e4e109b6170174460e2da74e4d348
#5 29.33 Get:82 http://mirrors.aliyun.com/debian buster/main amd64 libcurl3-gnutls amd64 7.64.0-4+deb10u2 [330 kB]
#5 CANCELED

#6 [stage-1 3/9] RUN git clone https://github.com/jumkey/redpill-lkm.git  -b develop  /opt/redpill-lkm &&    git clone https://github.com/jumkey/redpill-load.git -b develop /opt/redpill-load
#6 sha256:258f5fe9ac4d92ef4b23d30f16a5476df98927316677b81e036398ee6307405e
#6 CACHED

#9 [stage-1 4/9] COPY --from=extract E:/Git/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0/build/ /opt/toolkit_dev-broadwellnk-7.0.1-42218
#9 sha256:4276e444ee60f77408f61bb178b14fb73c7d361aee35e5cc152a89c012d4aa1a
#9 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount609316887/E:/Git/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0: lstat /var/lib/docker/tmp/buildkit-mount609316887/E:/Git/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0: no such file or directory
------
 > [stage-1 4/9] COPY --from=extract E:/Git/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0/build/ /opt/toolkit_dev-broadwellnk-7.0.1-42218:
------
failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount609316887/E:/Git/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0: lstat /var/lib/docker/tmp/buildkit-mount609316887/E:/Git/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0: no such file or directory

**Comment by tossp** [comment]
I haven't tested the compatibility under Windows system, and there is no plan to be compatible with Windows system for the time being
