### ISSUE TITLE
WSL编译出错

### ISSUE THREAD

**Issue by wangvic21** [tossp/redpill-tool-chain#62]
Building modules, stage 2.
RP-TARGET SPECIFIED AS dev v7
  MODPOST 1 modules
  CC      /opt/redpill-lkm/redpill.mod.o
  LD [M]  /opt/redpill-lkm/redpill.ko
make[2]: Leaving directory '/opt/toolkit_dev-apollolake-7.0.1-42218'
make[1]: Leaving directory '/opt/redpill-lkm'
#############################################
filename:       /opt/redpill-lkm/redpill.ko
license:        GPL
version:        v0.5-at-2022_03_05-14_09_21
author:         TTG
srcversion:     B8832A696B6882E8B0D5844
depends:        
retpoline:      Y
vermagic:       4.4.180+ SMP mod_unload 
#############################################
Using user_config.json:
cat: /opt/redpill-load/user_config.json: Is a directory
make: *** [Makefile:30: build_redpill_load] Error 1
vic@DESKTOP-DP5G2RD:~/redpill-tool-chain$ 

-----------------------------
是不是Win10 子系统不支持？我用虚拟机试试吧。

**Comment by tossp** [comment]
是的没有测试过wsl的兼容性，但是看你的报错是没有正确制作配置文件

**Comment by wangvic21** [comment]
同样的配置文件，我用了虚拟机，一次实现。 Vic Wang ***@***.*** 签名由 网易邮箱大师 定制 在2022年03月07日 09:06，TossPig 写道： 是的没有测试过wsl的兼容性，但是看你的报错是没有正确制作配置文件 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wangvic21** [comment]
build成功，在auto流程报错。

**Comment by tossp** [comment]
我这边没有相关的环境可以调试，我是直接在群晖上使用docker直接编译，有的时候偷懒就直接云编译了

**Comment by funkyirc** [comment]
i'm getting this error on my WSL2 ubuntu 20.04:
./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-dtb/rpext-index.json

Downloading

################################################################################################################# 100.0% -=O=- # # ## -=O=- # ### -=O=- #### -=O=- # ## -=O=- # # ## -=O=- # # # # -=O=- # # ## -=O=- # ### -=O=- #### -=O=- # ## -=O=- # # ## -=O=- # # # # -=O=- # # ## -=O=- # ### -=O=- #### -=O=- # ## -=O=- # # ## -=O=- # # # #curl: (28) Connection timed out after 300001 milliseconds

**Comment by Honanhui** [comment]
你好，我用你的编译工具编译918 添加了这些驱动，编译成功之后安装系统陷入无限循环安装，请问这是什么原因导致？
![ABD7209F-C402-49D2-AA52-731C8A313DCD](https://user-images.githubusercontent.com/101395925/158097808-54780d69-ad5f-4b61-9118-bfcffad772d0.png)

**Comment by Honanhui** [comment]
还有编译3617xs 添加一些驱动显示不被支持？但是pocopico大神的驱动源文件说明是支持3617xs42218的，怎么解决？
![DF74AE12-B548-4704-824B-58FBBD8EECAB](https://user-images.githubusercontent.com/101395925/158098044-5e9965a5-352f-426b-a83a-cac59001c20f.jpeg)

**Comment by Honanhui** [comment]
下载你的工具到本地编译，build成功，在auto流程报错，提示下面内容。架了梯子也是一样。我是在windows下远程连接乌班图来编译，windows开了v2ray。
![F1007AE5-7734-472F-929D-7EF2E3C3A47F](https://user-images.githubusercontent.com/101395925/158098134-9a5b7aec-bc4e-45b8-907e-3a69d053c438.jpeg)
![D3A4B43C-296E-4C07-BB60-7A1D4E1F8446](https://user-images.githubusercontent.com/101395925/158098146-d88e1671-8eb6-4064-bb34-b70864a118fc.jpeg)
