### ISSUE TITLE
Tossp, I hope you will add ds2422+ support

### ISSUE THREAD

**Issue by PeterSuh-Q3** [tossp/redpill-tool-chain#64]
I put the definition below in the global_config.json file with reference to ds1621+.
Although dtc editing and build were also completed, the SN of ds2422+ was used without the SN of ds2422+ and stopped at 55% during the DSM installation process, so it was no longer possible to proceed.
Can we just get ds2422+ SN GEN support?

,
    {
      "id": "ds2422p-7.0.1-42218",
      "platform_name": "DS2422+",
      "platform_version": "ds2422p-7.0.1-42218",
      "user_config_json": "ds2422p_user_config.json",
      "docker_base_image": "debian:10-slim",
      "compile_with": "toolkit_dev",
      "redpill_lkm_make_target": "dev-v7",
      "downloads": {
        "kernel": {
          "url": "https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/v1000-source/linux-4.4.x.txz/download",
          "sha256": "ac532ebb221d9c55f78236d57288ac31d410dde01f1453f60b0c502333fdf107"
        },
        "toolkit_dev": {
          "url": "https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.v1000-7.0.dev.txz/download",
          "sha256": "6108f9f7b7f0a13ee985314aef9419303375ab7ded4112be991590339b66ecd1"
        }
      },
      "redpill_lkm": {
        "source_url": "https://github.com/jumkey/redpill-lkm.git",
        "branch": "develop"
      },
      "redpill_load": {
        "source_url": "https://github.com/jumkey/redpill-load.git",
        "branch": "develop"
      }
    }

**Comment by tossp** [comment]
Support for `DS2422+` has not been added to the  [redpill-lkm](https://github.com/jumkey/redpill-lkm.git) project.

[redpill-load](https://github.com/jumkey/redpill-load.git) project's support for `DS2422+` model also seems to lack patches for `zImage` files

I'm not sure `DS2422+` will work.

`DS1621+` and `DS2422+` are on the same platform. You can try some.

You are very welcome to submit a PR to me after success. thx

**Comment by jumkey** [comment]
https://github.com/jumkey/redpill-lkm/tree/develop 其实已经加了，不过我没测试是不是能用
并且应该不需要bsp了
现在都在问这么用，等着你救命 https://xpenology.com/forum/topic/61702-yet-another-juns-mod/

**Comment by tossp** [comment]
> https://github.com/jumkey/redpill-lkm/tree/develop 其实已经加了，不过我没测试是不是能用 并且应该不需要bsp了 现在都在问这么用，等着你救命 https://xpenology.com/forum/topic/61702-yet-another-juns-mod/

哈？什么鬼，我一直在等你救命啊

https://github.com/jumkey/redpill-load/blob/develop/config/DS2422%2B/7.0.1-42218/config.json

确认不需要改`zImage`?

**Comment by jumkey** [comment]
我目前测试了DS918+跟DS920+是可以不用bsp了。Linux v4.x的型号应该都可以不用zImage了
不过./build-loader.sh脚本前面要加BRP_JUN_MOD=1
如
BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=user_config-ds918.json ./build-loader.sh 'DS918+' '7.0.1-42218'

**Comment by tossp** [comment]
> BR

十分钟后出一个测试版本

**Comment by tossp** [comment]
@jumkey 

https://github.com/tossp/redpill-tool-chain/runs/6435676646?check_suite_focus=true 测试失败

**Comment by jumkey** [comment]
v7.0.1版本的DS1621+ DS2422+ DS920+ DS918+
都加下这个吧
```json
      "build_env": {
        "jun_mod": 1,
        "debug": 1
      }
```

因为我在第一个分区加了个16M的`bzImage` 导致空间不够了

**Comment by tossp** [comment]
@jumkey 

貌似成功了，但中间有报
```
[#] Patching /opt/redpill-load/build/1652599664/pat-ds2422p_42218-unpacked/zImage to /opt/redpill-load/build/1652599664/zImage-patched... /bin/rm: cannot remove '/opt/redpill-load/build/1652599664/zImage-patched.tmp_src': No such file or directory
[*] Failed to delete src work file
```
https://github.com/tossp/redpill-tool-chain/runs/6439544524?check_suite_focus=true

我先调整发布了

**Comment by jumkey** [comment]
这个日志是正常的，因为没有bsp文件所以zImage-patched文件没有生成
