### ISSUE TITLE
Any best practice to update the redpill built image installed DSM system?

### ISSUE THREAD

**Issue by wey-gu** [tossp/redpill-tool-chain#65]
I noticed from reddit that someone shared their approach that:

- They removed all disks other than the first disk
- format the first disk and burn with the newly built redpill image
- plugin the other disks to let raid to sync

While my DSM is single disk deployed, how could we update the redpill loader itself, please(to potentially support a newer version of DSM in the future)?

Thanks!

**Comment by tossp** [comment]
个人感觉这个最佳实践意义不大

群晖自己为了保证数据安全策略，在安装系统过程中是不会去动数据分区的，数据分区的底层就是`raid`和`lvm`两种都是经过大量验证的成熟技术

我个人，是直接在群晖中编译镜像，并使用[synoboot.sh](https://github.com/tossp/redpill-tool-chain/blob/master/synoboot.sh)去直接写入镜像，并重启，但这个过程中会丢失`/root`中的文件或者其他一些自定义的系统文件。

dsm 6.0.2 是可以通过PXE引导，但dsm7似乎会在引导中写一些东西，这导致PXE引导失败，这个部分我没具体研究过

**Comment by wey-gu** [comment]
感谢回复，我后来才知道 pocopico 也弄了一个 https://github.com/pocopico/tinycore-redpill ，像你提到的一样相当于在群辉中编译，不过可以在一个小盘上（U盘）
一方面可以在 U 盘里，免去了我插拔硬盘（机箱很小，很麻烦），另一方面网卡 map 自动计算对我来说很方便，我感觉之后也许升级 tinycore 就是（安全起见可以拔出硬盘）重写 U 盘，启动再 build，再 migrate，还不确定虽然，不过 tinycore 真的挺适合我的场景。
