### ISSUE TITLE
编译成功之后安装系统陷入无限循环安装，请问这是什么原因导致？

### ISSUE THREAD

**Issue by Honanhui** [tossp/redpill-tool-chain#67]
你好，我用你的编译工具编译918 添加了这些驱动，编译成功之后安装系统陷入无限循环安装，请问这是什么原因导致？
![Uploading 32A26654-FEDE-4B4F-8FA4-50DF785B234F.png…]()

**Comment by tossp** [comment]
DS918+ 不支持mpt2sas和mpt3sas驱动，这个你应该在串口形象能看到

**Comment by Honanhui** [comment]
这个…不会呀😂😂，我都是按照教程来做的。这个串口信息怎么看？那我想用lsi2308直通卡，那得加哪个驱动？

**Comment by tossp** [comment]
换3615平台

**Comment by Honanhui** [comment]
我看别的大神做的918引导有添加LSI SAS3.0阵列卡驱动；这个不是mpt3sas？

**Comment by Honanhui** [comment]
3617 3622平台可以都可以支持是吗

**Comment by tossp** [comment]
> 我看别的大神做的918引导有添加LSI SAS3.0阵列卡驱动；这个不是mpt3sas？

你可以直接用别人编译好的版本



> 3617 3622平台可以都可以支持是吗

不确定，大概率可以，我没有测试环境这个需要你测试

**Comment by Honanhui** [comment]
别人做的引导搜索不到ip，只能自己来做了😂😂

**Comment by tossp** [comment]
祝你好运，期待可行方案反馈

**Comment by Honanhui** [comment]
好的

**Comment by Honanhui** [comment]
在线编译的话，我不是编辑920 1621是不需要添加jumkey.dtb这行代码的喔？

添加jumkey.misc这行代码是有什么作用的？
