### ISSUE TITLE
编译过程build成功，auto报错，出现以下问题

### ISSUE THREAD

**Issue by Honanhui** [tossp/redpill-tool-chain#69]
下载你的工具到本地编译，build成功，在auto流程报错，提示下面内容。架了梯子也是一样。我是在windows下远程连接乌班图来编译，windows开了v2ray。
![EA0BB2F7-6ECA-42B8-9FE9-B05996FB500F](https://user-images.githubusercontent.com/101395925/158099535-eda32c70-a9d3-4f92-a3db-6a840c151aa0.jpeg)
![E0DF7114-4A63-495A-A0C4-7717AF09B774](https://user-images.githubusercontent.com/101395925/158099543-c688582a-34c0-44bd-9750-98da27c35bb5.jpeg)

**Comment by tossp** [comment]
错误信息提示，ubuntu连接github失败。
你可以参考说明文档直接云编译

**Comment by Honanhui** [comment]
好的
