### ISSUE TITLE
制作ds3617xs-7.0.1-42218成功，但安装失败

### ISSUE THREAD

**Issue by psonys** [tossp/redpill-tool-chain#70]
编译ds3617xs-7.0.1-42218引导成功，但是无限重复安装系统
添加驱动
pocopico.igb
pocopico.igbvf
pocopico.ixgbevf
pocopico.mpt3sas
thethorgroup.boot-wait
thethorgroup.jg.virtio
thethorgroup.virtio

**Comment by tossp** [comment]
尝试取消`pocopico.mpt3sas`驱动

**Comment by yyxida** [comment]
ds3617xs-7.0.1-42218同样问题
驱动
pocopico.e1000e
pocopico.tg3
pocopico.vmxnet3
thethorgroup.boot-wait
thethorgroup.virtio

**Comment by tossp** [comment]
这就不清楚了，可以去社区ddr板块，继续讨论

**Comment by sjtuross** [comment]
安装时要阻止机器访问外网（最好是通过网关防火墙），否则会自动安装更新，重启后就处在recoverable的状态，我在PR#55里面提到了
