### ISSUE TITLE
大神你好，什么时候有空添加一下下3622 42218 u2或者u3的支持？

### ISSUE THREAD

**Issue by Honanhui** [tossp/redpill-tool-chain#76]
大神你好，什么时候有空添加一下3622 42218u2或者u3的支持？现在3622 42218更新update就陷入无限还原。。。我看这篇帖子里已经有作者更新到u2了，但是我知识有限，没研究明白怎么弄，所以想麻烦下大神你更新一下[的作者](https://xpenology.com/forum/topic/56872-develop-and-refine-the-ds3622xs-loader/page/8/)

**Comment by Honanhui** [comment]
连接：https://xpenology.com/forum/topic/56872-develop-and-refine-the-ds3622xs-loader/page/4/#comments

pocopico

With the kind assistance of [@buggy25200] and [@yanjun] i was able to create the required files and updated the loader for DS3622xs+ 7.01 u2.

**Comment by tossp** [comment]
暂时没找到合适的镜像资源，与驱动适配

**Comment by baccoui** [comment]
需要看驱动支持，目前只有918和ds3615支持比较好。如果你编译ds3622，可以尝试vi修改驱动文件，把引用ds3615的强制改为ds3622引用，看编译处理能否使用。

**Comment by Honanhui** [comment]
> 需要看驱动支持，目前只有918和ds3615支持比较好。如果你编译ds3622，可以尝试vi修改驱动文件，将引用3615的强制改为ds3622引用，看编译处理能否使用。

这个具体怎么操作？不懂😂😂，还有哪里可以找到驱动编译的教程？我想学一下自己编译驱动
