### ISSUE TITLE
之前反馈编译918 添加了这些驱动，编译成功之后安装系统陷入无限循环安装添加了redpill-boot-wait就好了

### ISSUE THREAD

**Issue by Honanhui** [tossp/redpill-tool-chain#78]
你好，我用你的编译工具编译918 添加了这些驱动，编译成功之后安装系统陷入无限循环安装，添加了https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json这段就能进系统了。。不再提示未安装系统
加了这些驱动acpid
redpill-virtio
         redpill-boot-wait
         e1000/rpext-index.json
       ixgbe/rpext-index.json
          i40e/rpext-index.json
        igb/rpext-index.json
        igbvf/rpext-index.json
        ixgbevf/rpext-index.json
      mpt3sas/rpext-index.json
        r8125/rpext-index.json
        r8168/rpext-index.json
      vmxnet3/rpext-index.json
       r8169/rpext-index.json

**Comment by tossp** [comment]
感谢反馈，稍后调整
