### ISSUE TITLE
docker基础镜像拉不到了

### ISSUE THREAD

**Issue by chenbeitang** [tossp/redpill-tool-chain#82]
生成引导执行docker的基础镜像需要docker授权

**Comment by tossp** [comment]
检查网络和配置，都是引用的公共镜像

**Comment by jiangmitiao** [comment]
https://registry.hub.docker.com/search?q=redpill-tool-chain&type=image
这里找不到镜像

**Comment by tossp** [comment]
这个镜像是要先本地制作的，不涉及服务器拉取

**Comment by baccoui** [comment]
build 和 auto 编译过程，建议全程科学上网。最后拉取pat有些慢，可以本地下载上传，加快auto最后一步的时间。
