### ISSUE TITLE
build报错，小白求助大佬

### ISSUE THREAD

**Issue by refined-fish** [tossp/redpill-tool-chain#84]
## 错误信息
Downloading Toolkit Dev 'docker/downloads/ds.broadwellnk-7.0.dev.txz'
[+] Building 1.8s (3/3) FINISHED                                                                                                                            
=> [internal] load build definition from Dockerfile
=> => transferring dockerfile: 2.81kB
=> [internal] load .dockerignore
=> => transferring context: 2B
=> ERROR [internal] load metadata for docker.io/library/debian:10-slim
> [internal] load metadata for docker.io/library/debian:10-slim:
failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

## 编译环境
Ubuntu 20.04.4 LTS
root用户，clone在root目录

**Comment by tossp** [comment]
没有遇到过这个错误，看着像docker的配置问题
