### ISSUE TITLE
/entrypoint.sh: line 5: git: command not found

### ISSUE THREAD

**Issue by yanweijum** [tossp/redpill-tool-chain#85]
执行sudo ./redpill_tool_chain.sh auto ds918p-7.0.1-42218时，报错/entrypoint.sh: line 5: git: command not found，啥情况？谢谢

**Comment by yanweijum** [comment]
我修改Dockerfile文件导致的

**Comment by tossp** [comment]
你没安装`git`

**Comment by yanweijum** [comment]
确认git已安装了，并且卸载重装仍不行，最终重装系统，在新系统上安装依赖后，再编译就很顺利了。
Ubuntu系统，安装依赖如下：
#安装git（编译所需）
apt-get install git
# 安装并启动docker（编译所需）
apt-get install -y docker.io
systemctl start docker
systemctl enable docker
docker version
# 安装jq（编译所需）
apt-get install -y jq
