### ISSUE TITLE
ds918 7.0.1 无限循环安装

### ISSUE THREAD

**Issue by MrVicent** [tossp/redpill-tool-chain#86]
pve 虚拟机安装ds918 7.0.1 
有一张sas2308硬盘卡 直通
目前安装重启后无限要求重新安装 而且只有e1000网卡是可用的
求教 到底哪出问题了？

添加的驱动如下
pocopico.e1000
thethorgroup.virtio
pocopico.vmxnet3
pocopico.mpt2sas
thethorgroup.boot-wait

又或者是 我pve设置有问题？
![image](https://user-images.githubusercontent.com/50162258/162160318-db92eabb-1e62-4046-b298-116721cd9694.png)

**Comment by psonys** [comment]
pocopico.mpt2sas
据说要删除这个驱动

**Comment by MrVicent** [comment]
> pocopico.mpt2sas 据说要删除这个驱动

但是。。。sas2308硬盘卡咋办呢
有其他驱动可以支持sas2308吗？

**Comment by tossp** [comment]
换平台

**Comment by MrVicent** [comment]
> 换平台

sad

**Comment by tossp** [comment]
你用pve，也可以考虑，磁盘直通

**Comment by tossp** [comment]
我pve7.1跑的很好啊
![image](https://user-images.githubusercontent.com/2138631/162615324-5d442bbe-2756-4ca1-a976-51eb8a04fd0d.png)

**Comment by MrVicent** [comment]
> 我pve7.1跑的很好啊 ![image](https://user-images.githubusercontent.com/2138631/162615324-5d442bbe-2756-4ca1-a976-51eb8a04fd0d.png)

现在的问题是 自编译的引导有问题 
网上又没找到同时有mpt2sas和virtio驱动的引导 就很愁人

**Comment by tossp** [comment]
mpt2sas 驱动在DS918下还不带virtio我都没成功过，换DS3xxx 吧
