### ISSUE TITLE
可否更新一下dev支持文件？

### ISSUE THREAD

**Issue by wanghaihua** [tossp/redpill-tool-chain#87]
尝试着将ds918的文件修改为ds716+，编译成功，但是引导出了问题，可否教授一下，添加新的机型支持，应该如何去做呢？比如说，编辑config文件，"patches": {
    "zlinux": [ "file1.bsp" ],
    "ramdisk": [ "file2.patch" ]，bsp的补丁有什么用，和如何自行制作呢？

**Comment by tossp** [comment]
这个文件是上游在制作，你可以参考这里https://github.com/jumkey/redpill-load
