### ISSUE TITLE
"error" text means ??

### ISSUE THREAD

**Issue by dolbycat** [tossp/redpill-tool-chain#91]
Hi~
I have successfully built DS920+ and DS1621+.

But I don't know what the little "error" text means.
I'd appreciate it if you could explain what it was.

![444](https://user-images.githubusercontent.com/91764546/162617496-ef542841-57f4-469e-a29b-9e63a953fe85.jpg)

I really like tossp's redpill-tool-chain.
thank you.

**Comment by tossp** [comment]
emmmm.....The script is not perfect enough and can be ignored here.
