### ISSUE TITLE
ds3615xs_42661 报错

### ISSUE THREAD

**Issue by keacefull** [tossp/redpill-tool-chain#94]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed
make: *** [build_redpill_load] Error 1

**Comment by keacefull** [comment]
我也不知道为什么  ds3622也是报这个错误。em........

**Comment by keacefull** [comment]
Ubuntu 20.4的系统

**Comment by ybist** [comment]
我ds3615也是这样，不知道怎么手动解压
Ubuntu 20.04

**Comment by tossp** [comment]
syno_extract_system_patch extract  依赖GLIBC，Ubuntu 20.04的GLIBC版本过低

手动解包思路

1. 先修改`global_config.json`中ds3615xs-7.1.0-4266的`docker_base_image`字段为`debian:10-slim`
1. 运行`./redpill_tool_chain.sh build ds3615xs-7.1.0-4266`,重制编译镜像
1. 运行`./redpill_tool_chain.sh auto ds3615xs-7.1.0-4266`,生成解密包，这个时候会报ko编译错误不管他，解密的PAT已经生成了
1. 修改`global_config.json`中ds3615xs-7.1.0-4266的`docker_base_image`字段为`debian:8-slim`
1. 运行`./redpill_tool_chain.sh build ds3615xs-7.1.0-4266`,重制编译镜像
1. 最后运行`./redpill_tool_chain.sh auto ds3615xs-7.1.0-4266`,引导镜像

嗯，大概就是这个思路，我还没试过

syno_extract_system_patch要在debian:10中才正常，ds3615xs需要在debian:8中才能编译

**Comment by tossp** [comment]
大概做了一个流程出来 https://github.com/tossp/redpill-tool-chain/actions/runs/2152707803

**Comment by keacefull** [comment]
我发现DS3622xs+ 在pve下运行貌似有问题，安装完成后一启动就自动关了。
