### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by psonys** [tossp/redpill-tool-chain#96]
之前提示效验错误已经修复，最新Git  clone以后编译还是报错，应该是扩展出错。

[!] Extension is already added (index exists at /opt/redpill-load/custom/extensions/redpill-boot-wait/redpill-boot-wait.json). For more info use "ext-manager.sh info redpill-boot-wait"

*** Process will exit ***
[!] Failed to install redpill.bootwait bundled extension - see errors above

*** Process will exit ***
make: *** [Makefile:34: build_redpill_load] Error 1

这个需要修改什么地方？

**Comment by tossp** [comment]
删除 custom/extensions 这个里面的所有文件

**Comment by psonys** [comment]
全新编译提示
[!] Failed to dump extension pocopico.ixgbe for platform ds918p_42661 as its recipe file cannot be retrieved. Isn't the extension misspelled or not supported on that platform?

*** Process will exit ***

[!] Failed to dump all extensions for ds918p_42661 platform to /opt/redpill-load/build/1649772777/custom-initrd/exts - see errors above

*** Process will exit ***
make: *** [Makefile:34: build_redpill_load] Error 1

**Comment by tossp** [comment]
编译的哪个版本？参考一下CI的过程代码

**Comment by psonys** [comment]
#############################################
./helper.sh
[#] Checking runtime for required tools... [OK]
[#] Found patched PAT file - Patch the PAT checksum
[#] Verifying /opt/redpill-load/cache/ds918p_42661.pat file... [OK]
[#] Test encryption pat results 0
pushd /opt/redpill-load && ./build-loader.sh 'DS918+' '7.1.0-42661'
/opt/redpill-load /opt
[#] Checking runtime for required tools... [OK]
[#] Updating extensions... 

[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json... 
[#] Downloading remote file https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json to /opt/redpill-load/custom/extensions/_new_ext_index.tmp_json
######################################################################################################################### 100.0%######################################################################################################################### 100.0%

[!] Extension is already added (index exists at /opt/redpill-load/custom/extensions/redpill-boot-wait/redpill-boot-wait.json). For more info use "ext-manager.sh info redpill-boot-wait"

*** Process will exit ***
[!] Failed to install redpill.bootwait bundled extension - see errors above

*** Process will exit ***
make: *** [Makefile:34: build_redpill_load] Error 1
编译最新的ds918，添加驱动就报错

**Comment by tossp** [comment]
https://github.com/tossp/redpill-tool-chain/runs/5984100579?check_suite_focus=true

**Comment by keacefull** [comment]
第二次编译的时候就会有这个问题，需要手动删除一次。
