### ISSUE TITLE
请问怎么加载ko驱动文件呢？

### ISSUE THREAD

**Issue by naoki66** [tossp/redpill-tool-chain#97]
部分硬件仅有驱动文件 ko，但是没有 .json文件。
例如X710万兆网卡的sriov

https://github.com/pocopico/4.4.180plus-modules/blob/main/i40evf.ko
https://github.com/pocopico/4.4.180plus-modules/blob/main/i40e.ko

下载使用
insmod /lib/modules/i40e.ko
insmod /lib/modules/i40evf.ko
ifconfig ethX up
正常，后面重启后失效。

**Comment by tossp** [comment]
两个方案
1. 在计划任务里面设置开机启动
2. 自己写json文件

**Comment by tossp** [comment]
你说的是这个吗？

https://github.com/pocopico/rp-ext/blob/main/i40e/rpext-index.json

**Comment by naoki66** [comment]
> 你说的是这个吗？
> 
> https://github.com/pocopico/rp-ext/blob/main/i40e/rpext-index.json

不是哦，这个是是原网卡驱动，sriov是额外的，带VF结尾的

**Comment by tossp** [comment]
仿照这个写就行了
