### ISSUE TITLE
Build failed. It seems the glibc is not OK.

### ISSUE THREAD

**Issue by joy999** [tossp/redpill-tool-chain#98]
[#] Unpacking /opt/redpill-load/cache/extract.tar.gz file to /tmp/synoesp... [OK]
[#] Unpacking /tmp/synoesp/rd.gz file to /tmp/extract... [OK]
[#] Use syno_extract_system_patch extract PAT... /usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/syno_extract_system_patch)
/usr/local/bin/syno_extract_system_patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libsodium.so)
[ERR]
[#] Repacking /tmp/repack.tar.gz file form /tmp/pat/... [ERR]
[!] Failed to unpack tar

/bin/tar: /tmp/pat/: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

*** Process will exit ***
Makefile:30: recipe for target 'build_redpill_load' failed

**Comment by tossp** [comment]
cc https://github.com/tossp/redpill-tool-chain/blob/7fb256a3bc27c88bca895287a26d4a440f0f77c5/.github/workflows/test.yml#L134

**Comment by joy999** [comment]
I replaced the "debian:8" to "debian:10". The "build" and "pat" are OK. But the "auto" failed. 


> ./redpill_tool_chain.sh auto ds3615xs-7.1.0-42661
> 
> Checking if redpill-lkm sources require pull.
>   Nothing to do.
> Check if redpill-load sources require pull.
>   Nothing to do.
> Lay back and enjoy the show: Magic is about to happen!
> make[1]: Entering directory '/opt/redpill-lkm'
> make -C /opt/toolkit_dev-bromolow-7.1.0-42661 M=/opt/redpill-lkm RP_MODULE_TARGET="dev" RP_MODULE_TARGET_VER="7" modules
> make[2]: Entering directory '/opt/toolkit_dev-bromolow-7.1.0-42661'
> /opt/toolkit_dev-bromolow-7.1.0-42661/arch/x86/Makefile:164: CONFIG_RETPOLINE=y, but not supported by the compiler. Toolchain update recommended.
> RP-TARGET SPECIFIED AS dev v7
>   CC [M]  /opt/redpill-lkm/compat/string_compat.o
> cc1: error: code model kernel does not support PIC mode
> make[3]: *** [scripts/Makefile.build:309: /opt/redpill-lkm/compat/string_compat.o] Error 1
> make[2]: *** [Makefile:1229: _module_/opt/redpill-lkm] Error 2
> make[2]: Leaving directory '/opt/toolkit_dev-bromolow-7.1.0-42661'
> make[1]: *** [Makefile:90: dev-v7] Error 2
> make[1]: Leaving directory '/opt/redpill-lkm'
> make: *** [Makefile:24: build_redpill_lkm] Error 2
>

**Comment by tossp** [comment]
https://github.com/tossp/redpill-tool-chain/issues/94#issuecomment-1095943785
