### ISSUE TITLE
920 在线编译如何添加dtb文件 

### ISSUE THREAD

**Issue by nb12nb34** [tossp/redpill-tool-chain#99]
请问下，用您的在线编译，920的dtb文件我已经生成了，在线编译的如何添加进去了。试了几个办法都没成功，希望大佬能够指导下，谢谢

**Comment by tossp** [comment]
编辑你的 `redpill-tool-chain/master/extensions/redpill-dtb.json`文件

1. `url`字段，应该为`https://github.com/nb12nb34/redpill-tool-chain/raw/master/extensions/redpill-dtb.json` 
1. 集成报错已经提醒你了，16行结尾少个逗号

**Comment by nb12nb34** [comment]
谢谢回复，问题解决了。。非常感谢！！

**Comment by tossp** [comment]
`url` 字段你并没有改，还是会退到公共版本

https://github.com/nb12nb34/redpill-tool-chain/blob/a728efbb5957e9ed3e9c709f9423c42fa44cd590/extensions/redpill-dtb.json#L3

**Comment by nb12nb34** [comment]
再次感谢！！已经修改并成功编译安装成功了。。
